use lumeicrm;

CREATE TABLE `op_auth_user` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `user_name` varchar(100) NOT NULL COMMENT '登陆名',
  `password` varchar(100) NOT NULL COMMENT '登陆密码',
  `salt` varchar(100) DEFAULT NULL COMMENT 'salt',
  `nick_name` varchar(100) NOT NULL COMMENT '用户名',
  `enabled` tinyint(4) NOT NULL COMMENT '是否启用 1-启用 0-禁用',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `delete_flag` tinyint(4) DEFAULT '0' COMMENT '是否删除 1-已删除 0-未删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `op_auth_user_role` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户主键ID',
  `role_id` varchar(32) DEFAULT NULL COMMENT '角色key',
  `role_name` varchar(32) DEFAULT NULL COMMENT '角色名',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `delete_flag` tinyint(4) DEFAULT '0' COMMENT '是否删除 1-已删除 0-未删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



create table `car_selling` (
  `id` varchar(32) not null,
  `user_id` varchar(32) default null,
  `sales_id` varchar(255) default null,
  `category` varchar(255) default null,
  `car_description` varchar(255) default null,
  `makes` varchar(255) default null,
  `model` varchar(255) default null,
  `is_new` smallint(6) default null comment 'new, used',
  `years` varchar(255) default null comment '选used就要填',
  `mileages` varchar(255) default null comment '选used就要填',
  `msrp` varchar(255) default null comment '选used就要填',
  `color` varchar(255) default null,
  `exterior` varchar(255) default null,
  `interior` varchar(255) default null,
  `comments` varchar(512) default null,
  `additional_information` varchar(255) default null,
  `credit_card_no` varchar(255) default null,
  `expiration_date` varchar(255) default null,
  `cvs` varchar(255) default null,
  `drivers_license` varchar(255) default null,
  `finance_down_payment` varchar(255) default null,
  `finance_rate` varchar(255) default null,
  `finance_terms` varchar(255) default null,
  `finance_monthly_pay` varchar(255) default null,
  `finance_comments` varchar(512) default null,
  `lease_additional_file` varchar(255) default null comment '1  2   3   etc (是否可以做成可以增加的类型）',
  `lease_down_payment` varchar(255) default null,
  `lease_terms` varchar(255) default null,
  `lease_monthly_pay` varchar(255) default null,
  `lease_comments` varchar(512) default null,
  `trade_in` varchar(255) default null comment 'yes/no, 若为no以下都不用填',
  `trade_in_makes` varchar(255) default null,
  `trade_in_model` varchar(255) default null,
  `trade_in_years` varchar(255) default null,
  `trade_in_mileage` varchar(255) default null,
  `trade_in_value` varchar(255) default null,
  `trade_in_color` varchar(255) default null,
  `trade_in_exterior` varchar(255) default null,
  `trade_in_interior` varchar(255) default null,
  `delete_flag` tinyint(4) default null,
  `create_user_id` varchar(32) default null,
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_user_id` varchar(32) default null,
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  primary key (`id`)
) engine=innodb default charset=utf8;

create table `emergency_contact` (
  `id` varchar(32) not null,
  `user_id` varchar(32) default null,
  `sales_id` varchar(32) default null,
  `dob` varchar(255) default null,
  `chinese_id` varchar(255) default null,
  `passport` varchar(255) default null,
  `university` varchar(255) default null,
  `school` varchar(255) default null,
  `department` varchar(255) default null,
  `school_email` varchar(255) default null,
  `personal_email` varchar(255) default null,
  `wechat_id` varchar(255) default null,
  `chinese_home_address` varchar(255) default null,
  `chinese_home_zip` varchar(255) default null,
  `chinese_home_telephone` varchar(255) default null,
  `chinese_home_cellphone` varchar(255) default null,
  `usa_home_address` varchar(255) default null,
  `usa_home_city` varchar(255) default null,
  `usa_home_state` varchar(255) default null,
  `usa_home_zip` varchar(255) default null,
  `usa_home_telephone` varchar(255) default null,
  `usa_home_cellphone` varchar(255) default null,
  `father_chinese_name` varchar(255) default null,
  `father_english_name` varchar(255) default null,
  `father_address` varchar(255) default null,
  `father_telephone` varchar(255) default null,
  `father_cellphone` varchar(255) default null,
  `father_wechat_id` varchar(255) default null,
  `mother_chinese_name` varchar(255) default null,
  `mother_english_name` varchar(255) default null,
  `mother_address` varchar(255) default null,
  `mother_telephone` varchar(255) default null,
  `mother_cellphone` varchar(255) default null,
  `mother_wechat_id` varchar(255) default null,
  `landlord_chinese_name` varchar(255) default null,
  `landlord_english_name` varchar(255) default null,
  `landlord_address` varchar(255) default null,
  `landlord_city` varchar(255) default null,
  `landlord_state` varchar(255) default null,
  `landlord_zip` varchar(255) default null,
  `landlord_telephone` varchar(255) default null,
  `landlord_cellphone` varchar(255) default null,
  `landlord_wechat_id` varchar(255) default null,
  `roommate_chinese_name` varchar(255) default null,
  `roommate_english_name` varchar(255) default null,
  `roommate_address` varchar(255) default null,
  `roommate_city` varchar(255) default null,
  `roommate_state` varchar(255) default null,
  `roommate_zip` varchar(255) default null,
  `roommate_telephone` varchar(255) default null,
  `roommate_cellphone` varchar(255) default null,
  `neighbor_chinese_name` varchar(255) default null,
  `neighbor_english_name` varchar(255) default null,
  `neighbor_address` varchar(255) default null,
  `neighbor_city` varchar(255) default null,
  `neighbor_state` varchar(255) default null,
  `neighbor_zip` varchar(255) default null,
  `neighbor_telephone` varchar(255) default null,
  `neighbor_cellphone` varchar(255) default null,
  `other_chinese_name` varchar(255) default null,
  `other_english_name` varchar(255) default null,
  `other_address` varchar(255) default null,
  `other_city` varchar(255) default null,
  `other_state` varchar(255) default null,
  `other_zip` varchar(255) default null,
  `other_telephone` varchar(255) default null,
  `other_cellphone` varchar(255) default null,
  `special` tinyint(4) default null,
  `special_comment` varchar(512) default null,
  `total` int(10) default 0,
  `used` int(10) default 0,
  `expiration_date` date default null,
  `delete_flag` tinyint(4) default null,
  `create_user_id` varchar(32) default null,
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_user_id` varchar(32) default null,
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  primary key (`id`)
) engine=innodb default charset=utf8;

create table `files` (
  `id` varchar(32) not null,
  `user_id` varchar(32) default null,
  `service_id` varchar(32) default null,
  `file_name` varchar(255) default null,
  `uri` varchar(255) default null,
  `delete_flag` tinyint(4) default null,
  `create_user_id` varchar(32) default null,
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_user_id` varchar(32) default null,
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  primary key (`id`)
) engine=innodb default charset=utf8;

create table `transaction` (
  `id` varchar(32) not null,
  `service_type` tinyint(3) default null,
  `user_id` varchar(32) default null,
  `service_id` varchar(32) default null,
  `delete_flag` tinyint(4) default null,
  `create_user_id` varchar(32) default null,
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_user_id` varchar(32) default null,
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  primary key (`id`)
) engine=innodb default charset=utf8;

create table `notes` (
  `id` varchar(32) not null,
  `note_service_type` tinyint(3) default null,
  `user_id` varchar(32) default null,
  `service_id` varchar(32) default null,
  `content` varchar(512) default null,
  `delete_flag` tinyint(4) default null,
  `create_user_id` varchar(32) default null,
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_user_id` varchar(32) default null,
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  primary key (`id`)
) engine=innodb default charset=utf8;

create table `profile` (
  `id` varchar(32) not null,
  `sales_id` varchar(32) default null,
  `name` varchar(128) default null,
  `gender` smallint(6) default null,
  `phone` varchar(64) default null,
  `email` varchar(128) default null,
  `wechat_id` varchar(64) default null,
  `street` varchar(256) default null,
  `city` varchar(64) default null,
  `state` varchar(64) default null,
  `zip_code` varchar(64) default null,
  `university` varchar(255) default null,
    `car_selling_status` varchar(64) default null,
    `finance_status` varchar(64) default null,
    `lease_status` varchar(64) default null,
  `rating` varchar(64) default null,
  `potential_buying_date`date default null,
  `service` varchar(255) default null comment 'car selling, emergency contact, car buying, car renal, cellphone, airport pickup, temporary house, aim',
  `delete_flag` tinyint(4) default null,
  `create_user_id` varchar(32) default null,
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_user_id` varchar(32) default null,
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  primary key (`id`)
) engine=innodb default charset=utf8;

CREATE TABLE `service_log` (
  `id` varchar(32) NOT NULL DEFAULT '',
  `user_id` varchar(32) DEFAULT NULL,
  `service_id` varchar(32) DEFAULT NULL,
  `service_type` tinyint(3) DEFAULT NULL,
  `content` varchar(255) DEFAULT NULL,
    `create_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `create_user_id` varchar(32) DEFAULT NULL,
`update_time` timestamp not null DEFAULT '2000-01-01 00:00:00',
  `update_user_id` varchar(32) DEFAULT NULL,
  `delete_flag` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
