CREATE TABLE `car_buying` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `Sales_Name` varchar(64) DEFAULT NULL,
  `Category` varchar(64) DEFAULT NULL,
  `Car_Description` varchar(64) DEFAULT NULL,
  `Makes` varchar(64) DEFAULT NULL,
  `Model` varchar(64) DEFAULT NULL,
  `is_New` smallint(6) DEFAULT NULL COMMENT 'new, used',
  `Years` varchar(64) DEFAULT NULL COMMENT '选used就要填',
  `Mileages` varchar(64) DEFAULT NULL COMMENT '选used就要填',
  `MSRP` varchar(64) DEFAULT NULL COMMENT '选used就要填',
  `Color` varchar(64) DEFAULT NULL,
  `Exterior` varchar(64) DEFAULT NULL,
  `Interior` varchar(64) DEFAULT NULL,
  `comments` varchar(64) DEFAULT NULL,
  `Additional_Information` varchar(64) DEFAULT NULL,
  `Credit_Card_no` varchar(64) DEFAULT NULL,
  `Expiration_Date` varchar(64) DEFAULT NULL,
  `CVS` varchar(64) DEFAULT NULL,
  `Drivers_License` varchar(64) DEFAULT NULL,
  `Finance_Down_Payment` varchar(64) DEFAULT NULL,
  `Finance_Rate` varchar(64) DEFAULT NULL,
  `Finance_Terms` varchar(64) DEFAULT NULL,
  `Finance_Monthly_Pay` varchar(64) DEFAULT NULL,
  `Finance_comments` varchar(64) DEFAULT NULL,
  `Lease_Additional_File` varchar(64) DEFAULT NULL COMMENT '1	2	3	etc	(是否可以做成可以增加的类型）',
  `Lease_Down_Payment` varchar(64) DEFAULT NULL,
  `Lease_Terms` varchar(64) DEFAULT NULL,
  `Lease_Monthly_Pay` varchar(64) DEFAULT NULL,
  `Lease_Comments` varchar(64) DEFAULT NULL,
  `Trade_in` varchar(64) DEFAULT NULL COMMENT 'yes/no, 若为no以下都不用填',
  `Trade_in_Makes` varchar(64) DEFAULT NULL,
  `Trade_in_Model` varchar(64) DEFAULT NULL,
  `Trade_in_Years` varchar(64) DEFAULT NULL,
  `Trade_in_Mileage` varchar(64) DEFAULT NULL,
  `trade_in_value` varchar(64) DEFAULT NULL,
  `Trade_in_Color` varchar(64) DEFAULT NULL,
  `Trade_in_Exterior` varchar(64) DEFAULT NULL,
  `Trade_in_Interior` varchar(64) DEFAULT NULL,
  `Notes` varchar(64) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `emergency_contact` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `Sales_Name` varchar(32) DEFAULT NULL,
  `DOB` varchar(32) DEFAULT NULL,
  `chinese_id` varchar(32) DEFAULT NULL,
  `passport` varchar(32) DEFAULT NULL,
  `University` varchar(32) DEFAULT NULL,
  `School` varchar(32) DEFAULT NULL,
  `Department` varchar(32) DEFAULT NULL,
  `school_email` varchar(32) DEFAULT NULL,
  `Personal_email` varchar(32) DEFAULT NULL,
  `Wechat_ID` varchar(32) DEFAULT NULL,
  `chinese_home_address` varchar(32) DEFAULT NULL,
  `chinese_home_zip` varchar(32) DEFAULT NULL,
  `chinese_home_telephone` varchar(32) DEFAULT NULL,
  `chinese_home_cellphone` varchar(32) DEFAULT NULL,
  `usa_home_address` varchar(32) DEFAULT NULL,
  `usa_home_city` varchar(32) DEFAULT NULL,
  `usa_home_state` varchar(32) DEFAULT NULL,
  `usa_home_zip` varchar(32) DEFAULT NULL,
  `usa_home_telephone` varchar(32) DEFAULT NULL,
  `usa_home_cellphone` varchar(32) DEFAULT NULL,
  `father_chinese_name` varchar(32) DEFAULT NULL,
  `father_english_name` varchar(32) DEFAULT NULL,
  `father_address` varchar(32) DEFAULT NULL,
  `father_telephone` varchar(32) DEFAULT NULL,
  `father_cellphone` varchar(32) DEFAULT NULL,
  `father_wechat_id` varchar(32) DEFAULT NULL,
  `mother_chinese_name` varchar(32) DEFAULT NULL,
  `mother_english_name` varchar(32) DEFAULT NULL,
  `mother_address` varchar(32) DEFAULT NULL,
  `mother_telephone` varchar(32) DEFAULT NULL,
  `mother_cellphone` varchar(32) DEFAULT NULL,
  `mother_wechat_id` varchar(32) DEFAULT NULL,
  `Landlord_chinese_name` varchar(32) DEFAULT NULL,
  `Landlord_english_name` varchar(32) DEFAULT NULL,
  `Landlord_address` varchar(32) DEFAULT NULL,
  `Landlord_city` varchar(32) DEFAULT NULL,
  `Landlord_state` varchar(32) DEFAULT NULL,
  `Landlord_zip` varchar(32) DEFAULT NULL,
  `Landlord_telephone` varchar(32) DEFAULT NULL,
  `Landlord_cellphone` varchar(32) DEFAULT NULL,
  `Landlord_wechat_id` varchar(32) DEFAULT NULL,
  `Roommate_chinese_name` varchar(32) DEFAULT NULL,
  `Roommate_english_name` varchar(32) DEFAULT NULL,
  `Roommate_address` varchar(32) DEFAULT NULL,
  `Roommate_city` varchar(32) DEFAULT NULL,
  `Roommate_state` varchar(32) DEFAULT NULL,
  `Roommate_zip` varchar(32) DEFAULT NULL,
  `Roommate_telephone` varchar(32) DEFAULT NULL,
  `Roommate_cellphone` varchar(32) DEFAULT NULL,
  `Neighbor_chinese_name` varchar(32) DEFAULT NULL,
  `Neighbor_english_name` varchar(32) DEFAULT NULL,
  `Neighbor_address` varchar(32) DEFAULT NULL,
  `Neighbor_city` varchar(32) DEFAULT NULL,
  `Neighbor_state` varchar(32) DEFAULT NULL,
  `Neighbor_zip` varchar(32) DEFAULT NULL,
  `Neighbor_telephone` varchar(32) DEFAULT NULL,
  `Neighbor_cellphone` varchar(32) DEFAULT NULL,
  `Other_chinese_name` varchar(32) DEFAULT NULL,
  `Other_english_name` varchar(32) DEFAULT NULL,
  `Other_address` varchar(32) DEFAULT NULL,
  `Other_city` varchar(32) DEFAULT NULL,
  `Other_state` varchar(32) DEFAULT NULL,
  `Other_zip` varchar(32) DEFAULT NULL,
  `Other_telephone` varchar(32) DEFAULT NULL,
  `Other_cellphone` varchar(32) DEFAULT NULL,
  `special` tinyint(4) DEFAULT NULL,
  `special_comment` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `files` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `service_type` varchar(32) DEFAULT NULL,
  `uri` varchar(255) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `notes` (
  `id` varchar(32) NOT NULL,
  `note_service_type` tinyint(3) DEFAULT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `content` varchar(255) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `profile` (
  `id` varchar(32) NOT NULL,
  `sales` varchar(32) DEFAULT NULL,
  `Name` varchar(32) DEFAULT NULL,
  `Gender` smallint(6) DEFAULT NULL,
  `Phone` varchar(16) DEFAULT NULL,
  `Email` varchar(64) DEFAULT NULL,
  `wechat_id` varchar(32) DEFAULT NULL,
  `Street` varchar(64) DEFAULT NULL,
  `City` varchar(64) DEFAULT NULL,
  `State` varchar(64) DEFAULT NULL,
  `Zip_Code` varchar(64) DEFAULT NULL,
  `University` varchar(64) DEFAULT NULL,
  `Status` varchar(64) DEFAULT NULL,
  `Deposit` varchar(64) DEFAULT NULL,
  `When_to_Buy` varchar(64) DEFAULT NULL,
  `Cash_Deal` varchar(64) DEFAULT NULL,
  `Finance` varchar(64) DEFAULT NULL,
  `Leasing` varchar(64) DEFAULT NULL,
  `Category` varchar(64) DEFAULT NULL,
  `Service` varchar(64) DEFAULT NULL COMMENT 'Car Buying, Car Selling, Car Renal, Cellphone, Airport Pickup, Temporary House, AIM, Emergency Contact',
  `effect_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `experiation_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Total_Events` int(11) DEFAULT NULL,
  `Used_Events` int(11) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

