CREATE TABLE `car_deal` (
  `id` varchar(32) NOT NULL,
  `customer_id` varchar(32) DEFAULT NULL,
  `sales_id` varchar(255) DEFAULT NULL,
  `deal_status` tinyint(3) DEFAULT NULL,
  `deal_date` date DEFAULT NULL,
  `rating` tinyint(3) DEFAULT NULL COMMENT '1:A, 2:B, 3:C',
  `deposit` tinyint(3) DEFAULT NULL,
  `credit_card_no` varchar(255) DEFAULT NULL,
  `is_new` tinyint(3) DEFAULT NULL COMMENT '1:new, 2:used',
  `years` varchar(255) DEFAULT NULL,
  `makes` varchar(255) DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `exterior_color` varchar(255) DEFAULT NULL,
  `interior_color` varchar(255) DEFAULT NULL,
  `msrp` varchar(255) DEFAULT NULL,
  `selling_price` varchar(255) DEFAULT NULL,
  `comments` varchar(2014) DEFAULT NULL,
  `method` tinyint(3) DEFAULT NULL COMMENT '1:cash deal, 2: finance, 3:lease',
  `down_payment` varchar(255) DEFAULT NULL,
  `rate` varchar(255) DEFAULT NULL,
  `terms` varchar(255) DEFAULT NULL,
  `monthly_pay` varchar(255) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `customer` (
  `id` varchar(32) NOT NULL,
  `sales_id` varchar(32) DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  `gender` smallint(6) DEFAULT NULL,
  `wechat` varchar(64) DEFAULT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `university` varchar(255) DEFAULT NULL,
  `major` varchar(255) DEFAULT NULL,
  `address` varchar(64) DEFAULT NULL,
  `zip_code` varchar(64) DEFAULT NULL,
  `service` varchar(255) DEFAULT NULL COMMENT 'car deal, car selling, car renal, cellphone, airport pickup, temporary house, aim, emergency contact',
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `emergency_contact` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `sales_id` varchar(32) DEFAULT NULL,
  `dob` varchar(255) DEFAULT NULL,
  `chinese_id` varchar(255) DEFAULT NULL,
  `passport` varchar(255) DEFAULT NULL,
  `university` varchar(255) DEFAULT NULL,
  `school` varchar(255) DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `school_email` varchar(255) DEFAULT NULL,
  `personal_email` varchar(255) DEFAULT NULL,
  `wechat_id` varchar(255) DEFAULT NULL,
  `chinese_home_address` varchar(255) DEFAULT NULL,
  `chinese_home_zip` varchar(255) DEFAULT NULL,
  `chinese_home_telephone` varchar(255) DEFAULT NULL,
  `chinese_home_cellphone` varchar(255) DEFAULT NULL,
  `usa_home_address` varchar(255) DEFAULT NULL,
  `usa_home_city` varchar(255) DEFAULT NULL,
  `usa_home_state` varchar(255) DEFAULT NULL,
  `usa_home_zip` varchar(255) DEFAULT NULL,
  `usa_home_telephone` varchar(255) DEFAULT NULL,
  `usa_home_cellphone` varchar(255) DEFAULT NULL,
  `father_chinese_name` varchar(255) DEFAULT NULL,
  `father_english_name` varchar(255) DEFAULT NULL,
  `father_address` varchar(255) DEFAULT NULL,
  `father_telephone` varchar(255) DEFAULT NULL,
  `father_cellphone` varchar(255) DEFAULT NULL,
  `father_wechat_id` varchar(255) DEFAULT NULL,
  `mother_chinese_name` varchar(255) DEFAULT NULL,
  `mother_english_name` varchar(255) DEFAULT NULL,
  `mother_address` varchar(255) DEFAULT NULL,
  `mother_telephone` varchar(255) DEFAULT NULL,
  `mother_cellphone` varchar(255) DEFAULT NULL,
  `mother_wechat_id` varchar(255) DEFAULT NULL,
  `landlord_chinese_name` varchar(255) DEFAULT NULL,
  `landlord_english_name` varchar(255) DEFAULT NULL,
  `landlord_address` varchar(255) DEFAULT NULL,
  `landlord_city` varchar(255) DEFAULT NULL,
  `landlord_state` varchar(255) DEFAULT NULL,
  `landlord_zip` varchar(255) DEFAULT NULL,
  `landlord_telephone` varchar(255) DEFAULT NULL,
  `landlord_cellphone` varchar(255) DEFAULT NULL,
  `landlord_wechat_id` varchar(255) DEFAULT NULL,
  `roommate_chinese_name` varchar(255) DEFAULT NULL,
  `roommate_english_name` varchar(255) DEFAULT NULL,
  `roommate_address` varchar(255) DEFAULT NULL,
  `roommate_city` varchar(255) DEFAULT NULL,
  `roommate_state` varchar(255) DEFAULT NULL,
  `roommate_zip` varchar(255) DEFAULT NULL,
  `roommate_telephone` varchar(255) DEFAULT NULL,
  `roommate_cellphone` varchar(255) DEFAULT NULL,
  `neighbor_chinese_name` varchar(255) DEFAULT NULL,
  `neighbor_english_name` varchar(255) DEFAULT NULL,
  `neighbor_address` varchar(255) DEFAULT NULL,
  `neighbor_city` varchar(255) DEFAULT NULL,
  `neighbor_state` varchar(255) DEFAULT NULL,
  `neighbor_zip` varchar(255) DEFAULT NULL,
  `neighbor_telephone` varchar(255) DEFAULT NULL,
  `neighbor_cellphone` varchar(255) DEFAULT NULL,
  `other_chinese_name` varchar(255) DEFAULT NULL,
  `other_english_name` varchar(255) DEFAULT NULL,
  `other_address` varchar(255) DEFAULT NULL,
  `other_city` varchar(255) DEFAULT NULL,
  `other_state` varchar(255) DEFAULT NULL,
  `other_zip` varchar(255) DEFAULT NULL,
  `other_telephone` varchar(255) DEFAULT NULL,
  `other_cellphone` varchar(255) DEFAULT NULL,
  `special` tinyint(4) DEFAULT NULL,
  `special_comment` varchar(512) DEFAULT NULL,
  `total` int(10) DEFAULT '0',
  `used` int(10) DEFAULT '0',
  `expiration_date` date DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `files` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `service_id` varchar(32) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `position` varchar(64) DEFAULT NULL,
  `uri` varchar(255) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` date DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `notes` (
  `id` varchar(32) NOT NULL,
  `note_service_type` tinyint(3) DEFAULT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `service_id` varchar(32) DEFAULT NULL,
  `content` varchar(512) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `op_auth_user` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `user_name` varchar(100) NOT NULL COMMENT '登陆名',
  `password` varchar(100) NOT NULL COMMENT '登陆密码',
  `salt` varchar(100) DEFAULT NULL COMMENT 'salt',
  `nick_name` varchar(100) NOT NULL COMMENT '用户名',
  `enabled` tinyint(4) NOT NULL COMMENT '是否启用 1-启用 0-禁用',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `delete_flag` tinyint(4) DEFAULT '0' COMMENT '是否删除 1-已删除 0-未删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `op_auth_user_role` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户主键ID',
  `role_id` varchar(32) DEFAULT NULL COMMENT '角色key',
  `role_name` varchar(32) DEFAULT NULL COMMENT '角色名',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `delete_flag` tinyint(4) DEFAULT '0' COMMENT '是否删除 1-已删除 0-未删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `service_log` (
  `id` varchar(32) NOT NULL DEFAULT '',
  `user_id` varchar(32) DEFAULT NULL,
  `service_id` varchar(32) DEFAULT NULL,
  `service_type` tinyint(3) DEFAULT NULL,
  `content` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `delete_flag` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `transaction` (
  `id` varchar(32) NOT NULL,
  `service_type` tinyint(3) DEFAULT NULL,
  `user_id` varchar(32) DEFAULT NULL,
  `service_id` varchar(32) DEFAULT NULL,
  `details` varchar(255) DEFAULT NULL,
  `delete_flag` tinyint(4) DEFAULT NULL,
  `create_user_id` varchar(32) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_user_id` varchar(32) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

