package com.lumei.crm.customer.biz;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.lumei.crm.commons.mybatis.support.Pagination;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.lumei.crm.commons.biz.support.CommonBusiness;
import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.commons.util.BeanUtils;
import com.lumei.crm.customer.dao.CarDealDao;
import com.lumei.crm.customer.dto.CarDeal;
import com.lumei.crm.customer.entity.TCarDeal;

/**
 * 
 * @generated by Code Generator v0.1
 * @Sat Aug 13 20:32:59 CST 2016
 */
@Service
public class CarDealBusiness extends CommonBusiness<CarDeal, TCarDeal, String> {

  @Autowired
  private CarDealDao carDealDao;

  private static Logger logger = LoggerFactory.getLogger(CarDealBusiness.class);

  /**
   * dto转换成po 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected TCarDeal toEntity(CarDeal model) {
    TCarDeal entity = new TCarDeal();
    BeanUtils.copy(model, entity);
    return entity;
  }

  /**
   * po转换成dto 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected CarDeal fromEntity(TCarDeal entity) {
    CarDeal model = new CarDeal();
    BeanUtils.copy(entity, model);
    return model;
  }

  /**
   * 为父类CommonBusiness注入Dao
   */
  @Override
  protected BaseDao<TCarDeal> getBaseDao() {
    return carDealDao;
  }

  /**
   * 为父类CommonBusiness注入logger
   */
  @Override
  protected Logger getLogger() {
    return logger;
  }

//  public Pagination<CarDeal> selectForList(String name, String phone, String wechat,
//      Byte rating, Byte dealStatus, Date dealDateStart, Date dealDateEnd,
//      int page, int limit){
  public Pagination<CarDeal> selectForList(Map param, int page, int limit){

    param.put("page", page-1);
    param.put("limit", limit);
    Integer count = carDealDao.countForList(param);

    Pagination<CarDeal> pg = Pagination.newInstance(page, limit);
    
    if(count==null||count<1){
      pg.setResult(new ArrayList());
      pg.setTotal(0);
      return pg;
    }
    pg.setTotal(count);
    List<TCarDeal> list = carDealDao.selectForList(param);
//    List<TCarDeal> list = carDealDao.selectForList(name, phone, wechat, rating,
//        dealStatus, dealDateStart, dealDateEnd, page, limit);
    if(list==null||list.size()<1){
      pg.setResult(new ArrayList());
      return pg;
    }
    List<CarDeal> result = new ArrayList();
    for(TCarDeal tmp:list){
      result.add(fromEntity(tmp));
    }
    pg.setResult(result);
    return pg;
  }
}
