package com.lumei.crm.customer.biz;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.lumei.crm.commons.biz.support.CommonBusiness;
import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.commons.util.BeanUtils;
import com.lumei.crm.customer.dao.FilesDao;
import com.lumei.crm.customer.dto.Files;
import com.lumei.crm.customer.entity.TFiles;

/**
 * 
 * @generated by Code Generator v0.1
 * @Sat Jul 30 23:58:18 CST 2016
 */
@Service
public class FilesBusiness extends CommonBusiness<Files, TFiles, String> {

  @Autowired
  private FilesDao filesDao;

  private static Logger logger = LoggerFactory.getLogger(FilesBusiness.class);

  /**
   * dto转换成po 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected TFiles toEntity(Files model) {
    TFiles entity = new TFiles();
    BeanUtils.copy(model, entity);
    return entity;
  }

  /**
   * po转换成dto 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected Files fromEntity(TFiles entity) {
    Files model = new Files();
    BeanUtils.copy(entity, model);
    return model;
  }

  /**
   * 为父类CommonBusiness注入Dao
   */
  @Override
  protected BaseDao<TFiles> getBaseDao() {
    return filesDao;
  }

  /**
   * 为父类CommonBusiness注入logger
   */
  @Override
  protected Logger getLogger() {
    return logger;
  }

}
