package com.lumei.crm.customer.biz;

import com.lumei.crm.commons.biz.support.CommonBusiness;
import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.commons.util.BeanUtils;
import com.lumei.crm.customer.dao.ServiceLogDao;
import com.lumei.crm.customer.entity.TServiceLog;
import com.lumei.crm.customer.dto.ServiceLog;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


/**
 * 
 * @generated by Code Generator v0.1
 * @Sun Aug 07 05:35:39 CST 2016
 */
@Service
public class ServiceLogBusiness extends CommonBusiness<ServiceLog, TServiceLog, String> {

  @Autowired
  private ServiceLogDao serviceLogDao;

  private static Logger logger = LoggerFactory.getLogger(ServiceLogBusiness.class);

  /**
   * dto转换成po 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected TServiceLog toEntity(ServiceLog model) {
    TServiceLog entity = new TServiceLog();
    BeanUtils.copy(model, entity);
    return entity;
  }

  /**
   * po转换成dto 根据实际情况重写此方法增加其他Bean属性的转换
   */
  @Override
  protected ServiceLog fromEntity(TServiceLog entity) {
    ServiceLog model = new ServiceLog();
    BeanUtils.copy(entity, model);
    return model;
  }

  /**
   * 为父类CommonBusiness注入Dao
   */
  @Override
  protected BaseDao<TServiceLog> getBaseDao() {
    return serviceLogDao;
  }

  /**
   * 为父类CommonBusiness注入logger
   */
  @Override
  protected Logger getLogger() {
    return logger;
  }

}
