package com.lumei.crm.customer.dto;

import java.io.Serializable;
import java.util.Date;

import com.lumei.crm.commons.biz.support.BaseModel;

// import com.cmbchina.commons.biz.support.BaseModel;
// import org.hibernate.validator.constraints.Length;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 13 20:32:59 CST 2016
 */
public class CarDealQueryParam implements Serializable {

  private static final long serialVersionUID = 1L;


  private String customerId;

  private String salesId;

  private String customerName;

  private String wechat;

  private String phone;

  private String salesName;

  private Byte dealStatus;

  private Byte rating;

  private Date dealDateStart;

  private Date dealDateEnd;


  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public String getSalesId() {
    return salesId;
  }

  public void setSalesId(String salesId) {
    this.salesId = salesId;
  }

  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public String getWechat() {
    return wechat;
  }

  public void setWechat(String wechat) {
    this.wechat = wechat;
  }

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public String getSalesName() {
    return salesName;
  }

  public void setSalesName(String salesName) {
    this.salesName = salesName;
  }

  public Byte getDealStatus() {
    return dealStatus;
  }

  public void setDealStatus(Byte dealStatus) {
    this.dealStatus = dealStatus;
  }

  public Byte getRating() {
    return rating;
  }

  public void setRating(Byte rating) {
    this.rating = rating;
  }

  public Date getDealDateStart() {
    return dealDateStart;
  }

  public void setDealDateStart(Date dealDateStart) {
    this.dealDateStart = dealDateStart;
  }

  public Date getDealDateEnd() {
    return dealDateEnd;
  }

  public void setDealDateEnd(Date dealDateEnd) {
    this.dealDateEnd = dealDateEnd;
  }


}
