package com.lumei.crm.customer.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 13 20:32:59 CST 2016
 */
public class CarInsuranceQueryParam implements Serializable {

  private static final long serialVersionUID = 1L;


  private String customerId;

  private String salesId;

  private String customerName;

  private String wechat;

  private String phone;

  private String salesName;

  private String orderColumn;
  
  private boolean orderDesc;
  
  private Date modifiedDateStart;
  private Date modifiedDateEnd;
  
  public Date getModifiedDateStart() {
	return modifiedDateStart;
}

public void setModifiedDateStart(Date modifiedDateStart) {
	this.modifiedDateStart = modifiedDateStart;
}

public Date getModifiedDateEnd() {
	return modifiedDateEnd;
}

public void setModifiedDateEnd(Date modifiedDateEnd) {
	this.modifiedDateEnd = modifiedDateEnd;
}

public String getOrderColumn() {
	return orderColumn;
}

public void setOrderColumn(String orderColumn) {
	this.orderColumn = orderColumn;
}

public boolean isOrderDesc() {
	return orderDesc;
}

public void setOrderDesc(boolean orderDesc) {
	this.orderDesc = orderDesc;
}

public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public String getSalesId() {
    return salesId;
  }

  public void setSalesId(String salesId) {
    this.salesId = salesId;
  }

  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public String getWechat() {
    return wechat;
  }

  public void setWechat(String wechat) {
    this.wechat = wechat;
  }

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public String getSalesName() {
    return salesName;
  }

  public void setSalesName(String salesName) {
    this.salesName = salesName;
  }

}
