package com.lumei.crm.customer.dto;

import java.io.Serializable;
import java.util.Date;
import com.lumei.crm.commons.biz.support.BaseModel;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sun Aug 28 13:20:17 CST 2016
 */
public class CarInsurance extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  private String customerName;
  private String salesName;
  private boolean readonly;
  private String latestNotes;
  private String wechat;
  
  /**
   * @field id
   */
  private String id;

  /**
   * @field customerId
   */
  private String customerId;

  /**
   * @field salesId
   */
  private String salesId;

  /**
   * @field carDealId
   */
  private String carDealId;

  /**
   * @field status
   */
  private Byte status;

  /**
   * @field effectiveDate
   */
  private Date effectiveDate;

  /**
   * @field creditCardNo
   */
  private String creditCardNo;

  /**
   * @field insuranceCompany
   */
  private String insuranceCompany;

  /**
   * @field terms
   */
  private String terms;

  /**
   * @field vinNo
   */
  private String vinNo;

  /**
   * @field price
   */
  private String price;

  /**
   * @field caseNo
   */
  private String caseNo;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @field createUserId
   */
  private String createUserId;

  /**
   * @field createTime
   */
  private Date createTime;

  /**
   * @field updateUserId
   */
  private String updateUserId;

  /**
   * @field updateTime
   */
  private Date updateTime;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return customerId
   */
  public String getCustomerId() {
    return customerId;
  }

  /**
   * @param customerId
   */
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  /**
   * @return salesId
   */
  public String getSalesId() {
    return salesId;
  }

  /**
   * @param salesId
   */
  public void setSalesId(String salesId) {
    this.salesId = salesId;
  }

  /**
   * @return carDealId
   */
  public String getCarDealId() {
    return carDealId;
  }

  /**
   * @param carDealId
   */
  public void setCarDealId(String carDealId) {
    this.carDealId = carDealId;
  }

  /**
   * @return status
   */
  public Byte getStatus() {
    return status;
  }

  /**
   * @param status
   */
  public void setStatus(Byte status) {
    this.status = status;
  }

  /**
   * @return effectiveDate
   */
  public Date getEffectiveDate() {
    return effectiveDate;
  }

  /**
   * @param effectiveDate
   */
  public void setEffectiveDate(Date effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  /**
   * @return creditCardNo
   */
  public String getCreditCardNo() {
    return creditCardNo;
  }

  /**
   * @param creditCardNo
   */
  public void setCreditCardNo(String creditCardNo) {
    this.creditCardNo = creditCardNo;
  }

  /**
   * @return insuranceCompany
   */
  public String getInsuranceCompany() {
    return insuranceCompany;
  }

  /**
   * @param insuranceCompany
   */
  public void setInsuranceCompany(String insuranceCompany) {
    this.insuranceCompany = insuranceCompany;
  }

  /**
   * @return terms
   */
  public String getTerms() {
    return terms;
  }

  /**
   * @param terms
   */
  public void setTerms(String terms) {
    this.terms = terms;
  }

  /**
   * @return vinNo
   */
  public String getVinNo() {
    return vinNo;
  }

  /**
   * @param vinNo
   */
  public void setVinNo(String vinNo) {
    this.vinNo = vinNo;
  }

  /**
   * @return price
   */
  public String getPrice() {
    return price;
  }

  /**
   * @param price
   */
  public void setPrice(String price) {
    this.price = price;
  }

  /**
   * @return caseNo
   */
  public String getCaseNo() {
    return caseNo;
  }

  /**
   * @param caseNo
   */
  public void setCaseNo(String caseNo) {
    this.caseNo = caseNo;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  /**
   * @return createUserId
   */
  public String getCreateUserId() {
    return createUserId;
  }

  /**
   * @param createUserId
   */
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return updateUserId
   */
  public String getUpdateUserId() {
    return updateUserId;
  }

  /**
   * @param updateUserId
   */
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }

  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

public String getCustomerName() {
	return customerName;
}

public void setCustomerName(String customerName) {
	this.customerName = customerName;
}

public String getSalesName() {
	return salesName;
}

public void setSalesName(String salesName) {
	this.salesName = salesName;
}

public boolean isReadonly() {
	return readonly;
}

public void setReadonly(boolean readonly) {
	this.readonly = readonly;
}

public String getLatestNotes() {
	return latestNotes;
}

public void setLatestNotes(String latestNotes) {
	this.latestNotes = latestNotes;
}

public String getWechat() {
	return wechat;
}

public void setWechat(String wechat) {
	this.wechat = wechat;
}

}
