package com.lumei.crm.customer.dto;

import java.io.Serializable;
import java.util.Date;
// import com.cmbchina.commons.biz.support.BaseModel;
// import org.hibernate.validator.constraints.Length;

import com.lumei.crm.commons.biz.support.BaseModel;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 13 20:32:59 CST 2016
 */
public class Customer extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * @field id
   */
  //@Length(min = 1, max = 0, message = "ID长度为0")
  private String id;

  /**
   * @field salesId
   */
  //@Length(min = 1, max = 0, message = "SALES_ID长度为0")
  private String salesId;

  /**
   * @field name
   */
  //@Length(min = 1, max = 0, message = "NAME长度为0")
  private String name;

  /**
   * @field gender
   */
  private Short gender;

  /**
   * @field wechat
   */
  //@Length(min = 1, max = 0, message = "WECHAT长度为0")
  private String wechat;

  /**
   * @field phone
   */
  //@Length(min = 1, max = 0, message = "PHONE长度为0")
  private String phone;

  /**
   * @field email
   */
  //@Length(min = 1, max = 0, message = "EMAIL长度为0")
  private String email;

  /**
   * @field university
   */
  //@Length(min = 1, max = 0, message = "UNIVERSITY长度为0")
  private String university;

  /**
   * @field major
   */
  //@Length(min = 1, max = 0, message = "MAJOR长度为0")
  private String major;

  /**
   * @field address
   */
  //@Length(min = 1, max = 0, message = "ADDRESS长度为0")
  private String address;

  /**
   * @field zipCode
   */
  //@Length(min = 1, max = 0, message = "ZIP_CODE长度为0")
  private String zipCode;

  /**
   * @field service
   */
  //@Length(min = 1, max = 0, message = "SERVICE长度为0")
  private String service;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @field createUserId
   */
  //@Length(min = 1, max = 0, message = "CREATE_USER_ID长度为0")
  private String createUserId;

  /**
   * @field createTime
   */
  private Date createTime;

  /**
   * @field updateUserId
   */
  //@Length(min = 1, max = 0, message = "UPDATE_USER_ID长度为0")
  private String updateUserId;

  /**
   * @field updateTime
   */
  private Date updateTime;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return salesId
   */
  public String getSalesId() {
    return salesId;
  }

  /**
   * @param salesId
   */
  public void setSalesId(String salesId) {
    this.salesId = salesId;
  }

  /**
   * @return name
   */
  public String getName() {
    return name;
  }

  /**
   * @param name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * @return gender
   */
  public Short getGender() {
    return gender;
  }

  /**
   * @param gender
   */
  public void setGender(Short gender) {
    this.gender = gender;
  }

  /**
   * @return wechat
   */
  public String getWechat() {
    return wechat;
  }

  /**
   * @param wechat
   */
  public void setWechat(String wechat) {
    this.wechat = wechat;
  }

  /**
   * @return phone
   */
  public String getPhone() {
    return phone;
  }

  /**
   * @param phone
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * @return email
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param email
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * @return university
   */
  public String getUniversity() {
    return university;
  }

  /**
   * @param university
   */
  public void setUniversity(String university) {
    this.university = university;
  }

  /**
   * @return major
   */
  public String getMajor() {
    return major;
  }

  /**
   * @param major
   */
  public void setMajor(String major) {
    this.major = major;
  }

  /**
   * @return address
   */
  public String getAddress() {
    return address;
  }

  /**
   * @param address
   */
  public void setAddress(String address) {
    this.address = address;
  }

  /**
   * @return zipCode
   */
  public String getZipCode() {
    return zipCode;
  }

  /**
   * @param zipCode
   */
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  /**
   * @return service
   */
  public String getService() {
    return service;
  }

  /**
   * @param service
   */
  public void setService(String service) {
    this.service = service;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  /**
   * @return createUserId
   */
  public String getCreateUserId() {
    return createUserId;
  }

  /**
   * @param createUserId
   */
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return updateUserId
   */
  public String getUpdateUserId() {
    return updateUserId;
  }

  /**
   * @param updateUserId
   */
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }

  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

}
