package com.lumei.crm.customer.dto;

import java.io.Serializable;
import java.util.Date;
// import com.cmbchina.commons.biz.support.BaseModel;
// import org.hibernate.validator.constraints.Length;

import com.lumei.crm.commons.biz.support.BaseModel;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 06 12:01:34 CST 2016
 */
public class EmergencyContact extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  private boolean readonly;

  public boolean isReadonly() {
    return readonly;
  }

  public void setReadonly(boolean readonly) {
    this.readonly = readonly;
  }
  
  private String salesName;
  
  public String getSalesName() {
	return salesName;
}

public void setSalesName(String salesName) {
	this.salesName = salesName;
}

/**
   * @field id
   */
  //@Length(min = 1, max = 0, message = "ID长度为0")
  private String id;

  /**
   * @field userId
   */
  //@Length(min = 1, max = 0, message = "USER_ID长度为0")
  private String userId;

  /**
   * @field salesId
   */
  //@Length(min = 1, max = 0, message = "SALES_ID长度为0")
  private String salesId;

  /**
   * @field dob
   */
  //@Length(min = 1, max = 0, message = "DOB长度为0")
  private String dob;

  /**
   * @field chineseId
   */
  //@Length(min = 1, max = 0, message = "CHINESE_ID长度为0")
  private String chineseId;

  /**
   * @field passport
   */
  //@Length(min = 1, max = 0, message = "PASSPORT长度为0")
  private String passport;

  /**
   * @field university
   */
  //@Length(min = 1, max = 0, message = "UNIVERSITY长度为0")
  private String university;

  /**
   * @field school
   */
  //@Length(min = 1, max = 0, message = "SCHOOL长度为0")
  private String school;

  /**
   * @field department
   */
  //@Length(min = 1, max = 0, message = "DEPARTMENT长度为0")
  private String department;

  /**
   * @field schoolEmail
   */
  //@Length(min = 1, max = 0, message = "SCHOOL_EMAIL长度为0")
  private String schoolEmail;

  /**
   * @field personalEmail
   */
  //@Length(min = 1, max = 0, message = "PERSONAL_EMAIL长度为0")
  private String personalEmail;

  /**
   * @field wechatId
   */
  //@Length(min = 1, max = 0, message = "WECHAT_ID长度为0")
  private String wechatId;

  /**
   * @field chineseHomeAddress
   */
  //@Length(min = 1, max = 0, message = "CHINESE_HOME_ADDRESS长度为0")
  private String chineseHomeAddress;

  /**
   * @field chineseHomeZip
   */
  //@Length(min = 1, max = 0, message = "CHINESE_HOME_ZIP长度为0")
  private String chineseHomeZip;

  /**
   * @field chineseHomeTelephone
   */
  //@Length(min = 1, max = 0, message = "CHINESE_HOME_TELEPHONE长度为0")
  private String chineseHomeTelephone;

  /**
   * @field chineseHomeCellphone
   */
  //@Length(min = 1, max = 0, message = "CHINESE_HOME_CELLPHONE长度为0")
  private String chineseHomeCellphone;

  /**
   * @field usaHomeAddress
   */
  //@Length(min = 1, max = 0, message = "USA_HOME_ADDRESS长度为0")
  private String usaHomeAddress;

  /**
   * @field usaHomeCity
   */
  //@Length(min = 1, max = 0, message = "USA_HOME_CITY长度为0")
  private String usaHomeCity;

  /**
   * @field usaHomeState
   */
  //@Length(min = 1, max = 0, message = "USA_HOME_STATE长度为0")
  private String usaHomeState;

  /**
   * @field usaHomeZip
   */
  //@Length(min = 1, max = 0, message = "USA_HOME_ZIP长度为0")
  private String usaHomeZip;

  /**
   * @field usaHomeTelephone
   */
  //@Length(min = 1, max = 0, message = "USA_HOME_TELEPHONE长度为0")
  private String usaHomeTelephone;

  /**
   * @field usaHomeCellphone
   */
  //@Length(min = 1, max = 0, message = "USA_HOME_CELLPHONE长度为0")
  private String usaHomeCellphone;

  /**
   * @field fatherChineseName
   */
  //@Length(min = 1, max = 0, message = "FATHER_CHINESE_NAME长度为0")
  private String fatherChineseName;

  /**
   * @field fatherEnglishName
   */
  //@Length(min = 1, max = 0, message = "FATHER_ENGLISH_NAME长度为0")
  private String fatherEnglishName;

  /**
   * @field fatherAddress
   */
  //@Length(min = 1, max = 0, message = "FATHER_ADDRESS长度为0")
  private String fatherAddress;

  /**
   * @field fatherTelephone
   */
  //@Length(min = 1, max = 0, message = "FATHER_TELEPHONE长度为0")
  private String fatherTelephone;

  /**
   * @field fatherCellphone
   */
  //@Length(min = 1, max = 0, message = "FATHER_CELLPHONE长度为0")
  private String fatherCellphone;

  /**
   * @field fatherWechatId
   */
  //@Length(min = 1, max = 0, message = "FATHER_WECHAT_ID长度为0")
  private String fatherWechatId;

  /**
   * @field motherChineseName
   */
  //@Length(min = 1, max = 0, message = "MOTHER_CHINESE_NAME长度为0")
  private String motherChineseName;

  /**
   * @field motherEnglishName
   */
  //@Length(min = 1, max = 0, message = "MOTHER_ENGLISH_NAME长度为0")
  private String motherEnglishName;

  /**
   * @field motherAddress
   */
  //@Length(min = 1, max = 0, message = "MOTHER_ADDRESS长度为0")
  private String motherAddress;

  /**
   * @field motherTelephone
   */
  //@Length(min = 1, max = 0, message = "MOTHER_TELEPHONE长度为0")
  private String motherTelephone;

  /**
   * @field motherCellphone
   */
  //@Length(min = 1, max = 0, message = "MOTHER_CELLPHONE长度为0")
  private String motherCellphone;

  /**
   * @field motherWechatId
   */
  //@Length(min = 1, max = 0, message = "MOTHER_WECHAT_ID长度为0")
  private String motherWechatId;

  /**
   * @field landlordChineseName
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_CHINESE_NAME长度为0")
  private String landlordChineseName;

  /**
   * @field landlordEnglishName
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_ENGLISH_NAME长度为0")
  private String landlordEnglishName;

  /**
   * @field landlordAddress
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_ADDRESS长度为0")
  private String landlordAddress;

  /**
   * @field landlordCity
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_CITY长度为0")
  private String landlordCity;

  /**
   * @field landlordState
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_STATE长度为0")
  private String landlordState;

  /**
   * @field landlordZip
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_ZIP长度为0")
  private String landlordZip;

  /**
   * @field landlordTelephone
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_TELEPHONE长度为0")
  private String landlordTelephone;

  /**
   * @field landlordCellphone
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_CELLPHONE长度为0")
  private String landlordCellphone;

  /**
   * @field landlordWechatId
   */
  //@Length(min = 1, max = 0, message = "LANDLORD_WECHAT_ID长度为0")
  private String landlordWechatId;

  /**
   * @field roommateChineseName
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_CHINESE_NAME长度为0")
  private String roommateChineseName;

  /**
   * @field roommateEnglishName
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_ENGLISH_NAME长度为0")
  private String roommateEnglishName;

  /**
   * @field roommateAddress
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_ADDRESS长度为0")
  private String roommateAddress;

  /**
   * @field roommateCity
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_CITY长度为0")
  private String roommateCity;

  /**
   * @field roommateState
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_STATE长度为0")
  private String roommateState;

  /**
   * @field roommateZip
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_ZIP长度为0")
  private String roommateZip;

  /**
   * @field roommateTelephone
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_TELEPHONE长度为0")
  private String roommateTelephone;

  /**
   * @field roommateCellphone
   */
  //@Length(min = 1, max = 0, message = "ROOMMATE_CELLPHONE长度为0")
  private String roommateCellphone;

  /**
   * @field neighborChineseName
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_CHINESE_NAME长度为0")
  private String neighborChineseName;

  /**
   * @field neighborEnglishName
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_ENGLISH_NAME长度为0")
  private String neighborEnglishName;

  /**
   * @field neighborAddress
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_ADDRESS长度为0")
  private String neighborAddress;

  /**
   * @field neighborCity
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_CITY长度为0")
  private String neighborCity;

  /**
   * @field neighborState
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_STATE长度为0")
  private String neighborState;

  /**
   * @field neighborZip
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_ZIP长度为0")
  private String neighborZip;

  /**
   * @field neighborTelephone
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_TELEPHONE长度为0")
  private String neighborTelephone;

  /**
   * @field neighborCellphone
   */
  //@Length(min = 1, max = 0, message = "NEIGHBOR_CELLPHONE长度为0")
  private String neighborCellphone;

  /**
   * @field otherChineseName
   */
  //@Length(min = 1, max = 0, message = "OTHER_CHINESE_NAME长度为0")
  private String otherChineseName;

  /**
   * @field otherEnglishName
   */
  //@Length(min = 1, max = 0, message = "OTHER_ENGLISH_NAME长度为0")
  private String otherEnglishName;

  /**
   * @field otherAddress
   */
  //@Length(min = 1, max = 0, message = "OTHER_ADDRESS长度为0")
  private String otherAddress;

  /**
   * @field otherCity
   */
  //@Length(min = 1, max = 0, message = "OTHER_CITY长度为0")
  private String otherCity;

  /**
   * @field otherState
   */
  //@Length(min = 1, max = 0, message = "OTHER_STATE长度为0")
  private String otherState;

  /**
   * @field otherZip
   */
  //@Length(min = 1, max = 0, message = "OTHER_ZIP长度为0")
  private String otherZip;

  /**
   * @field otherTelephone
   */
  //@Length(min = 1, max = 0, message = "OTHER_TELEPHONE长度为0")
  private String otherTelephone;

  /**
   * @field otherCellphone
   */
  //@Length(min = 1, max = 0, message = "OTHER_CELLPHONE长度为0")
  private String otherCellphone;

  /**
   * @field special
   */
  private Byte special;

  /**
   * @field specialComment
   */
  //@Length(min = 1, max = 0, message = "SPECIAL_COMMENT长度为0")
  private String specialComment;

  /**
   * @field total
   */
  private Integer total;

  /**
   * @field used
   */
  private Integer used;

  /**
   * @field expirationDate
   */
  private Date expirationDate;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @field createUserId
   */
  //@Length(min = 1, max = 0, message = "CREATE_USER_ID长度为0")
  private String createUserId;

  /**
   * @field createTime
   */
  private Date createTime;

  /**
   * @field updateUserId
   */
  //@Length(min = 1, max = 0, message = "UPDATE_USER_ID长度为0")
  private String updateUserId;

  /**
   * @field updateTime
   */
  private Date updateTime;

  private String notes;
  
  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return userId
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param userId
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return salesId
   */
  public String getSalesId() {
    return salesId;
  }

  /**
   * @param salesId
   */
  public void setSalesId(String salesId) {
    this.salesId = salesId;
  }

  /**
   * @return dob
   */
  public String getDob() {
    return dob;
  }

  /**
   * @param dob
   */
  public void setDob(String dob) {
    this.dob = dob;
  }

  /**
   * @return chineseId
   */
  public String getChineseId() {
    return chineseId;
  }

  /**
   * @param chineseId
   */
  public void setChineseId(String chineseId) {
    this.chineseId = chineseId;
  }

  /**
   * @return passport
   */
  public String getPassport() {
    return passport;
  }

  /**
   * @param passport
   */
  public void setPassport(String passport) {
    this.passport = passport;
  }

  /**
   * @return university
   */
  public String getUniversity() {
    return university;
  }

  /**
   * @param university
   */
  public void setUniversity(String university) {
    this.university = university;
  }

  /**
   * @return school
   */
  public String getSchool() {
    return school;
  }

  /**
   * @param school
   */
  public void setSchool(String school) {
    this.school = school;
  }

  /**
   * @return department
   */
  public String getDepartment() {
    return department;
  }

  /**
   * @param department
   */
  public void setDepartment(String department) {
    this.department = department;
  }

  /**
   * @return schoolEmail
   */
  public String getSchoolEmail() {
    return schoolEmail;
  }

  /**
   * @param schoolEmail
   */
  public void setSchoolEmail(String schoolEmail) {
    this.schoolEmail = schoolEmail;
  }

  /**
   * @return personalEmail
   */
  public String getPersonalEmail() {
    return personalEmail;
  }

  /**
   * @param personalEmail
   */
  public void setPersonalEmail(String personalEmail) {
    this.personalEmail = personalEmail;
  }

  /**
   * @return wechatId
   */
  public String getWechatId() {
    return wechatId;
  }

  /**
   * @param wechatId
   */
  public void setWechatId(String wechatId) {
    this.wechatId = wechatId;
  }

  /**
   * @return chineseHomeAddress
   */
  public String getChineseHomeAddress() {
    return chineseHomeAddress;
  }

  /**
   * @param chineseHomeAddress
   */
  public void setChineseHomeAddress(String chineseHomeAddress) {
    this.chineseHomeAddress = chineseHomeAddress;
  }

  /**
   * @return chineseHomeZip
   */
  public String getChineseHomeZip() {
    return chineseHomeZip;
  }

  /**
   * @param chineseHomeZip
   */
  public void setChineseHomeZip(String chineseHomeZip) {
    this.chineseHomeZip = chineseHomeZip;
  }

  /**
   * @return chineseHomeTelephone
   */
  public String getChineseHomeTelephone() {
    return chineseHomeTelephone;
  }

  /**
   * @param chineseHomeTelephone
   */
  public void setChineseHomeTelephone(String chineseHomeTelephone) {
    this.chineseHomeTelephone = chineseHomeTelephone;
  }

  /**
   * @return chineseHomeCellphone
   */
  public String getChineseHomeCellphone() {
    return chineseHomeCellphone;
  }

  /**
   * @param chineseHomeCellphone
   */
  public void setChineseHomeCellphone(String chineseHomeCellphone) {
    this.chineseHomeCellphone = chineseHomeCellphone;
  }

  /**
   * @return usaHomeAddress
   */
  public String getUsaHomeAddress() {
    return usaHomeAddress;
  }

  /**
   * @param usaHomeAddress
   */
  public void setUsaHomeAddress(String usaHomeAddress) {
    this.usaHomeAddress = usaHomeAddress;
  }

  /**
   * @return usaHomeCity
   */
  public String getUsaHomeCity() {
    return usaHomeCity;
  }

  /**
   * @param usaHomeCity
   */
  public void setUsaHomeCity(String usaHomeCity) {
    this.usaHomeCity = usaHomeCity;
  }

  /**
   * @return usaHomeState
   */
  public String getUsaHomeState() {
    return usaHomeState;
  }

  /**
   * @param usaHomeState
   */
  public void setUsaHomeState(String usaHomeState) {
    this.usaHomeState = usaHomeState;
  }

  /**
   * @return usaHomeZip
   */
  public String getUsaHomeZip() {
    return usaHomeZip;
  }

  /**
   * @param usaHomeZip
   */
  public void setUsaHomeZip(String usaHomeZip) {
    this.usaHomeZip = usaHomeZip;
  }

  /**
   * @return usaHomeTelephone
   */
  public String getUsaHomeTelephone() {
    return usaHomeTelephone;
  }

  /**
   * @param usaHomeTelephone
   */
  public void setUsaHomeTelephone(String usaHomeTelephone) {
    this.usaHomeTelephone = usaHomeTelephone;
  }

  /**
   * @return usaHomeCellphone
   */
  public String getUsaHomeCellphone() {
    return usaHomeCellphone;
  }

  /**
   * @param usaHomeCellphone
   */
  public void setUsaHomeCellphone(String usaHomeCellphone) {
    this.usaHomeCellphone = usaHomeCellphone;
  }

  /**
   * @return fatherChineseName
   */
  public String getFatherChineseName() {
    return fatherChineseName;
  }

  /**
   * @param fatherChineseName
   */
  public void setFatherChineseName(String fatherChineseName) {
    this.fatherChineseName = fatherChineseName;
  }

  /**
   * @return fatherEnglishName
   */
  public String getFatherEnglishName() {
    return fatherEnglishName;
  }

  /**
   * @param fatherEnglishName
   */
  public void setFatherEnglishName(String fatherEnglishName) {
    this.fatherEnglishName = fatherEnglishName;
  }

  /**
   * @return fatherAddress
   */
  public String getFatherAddress() {
    return fatherAddress;
  }

  /**
   * @param fatherAddress
   */
  public void setFatherAddress(String fatherAddress) {
    this.fatherAddress = fatherAddress;
  }

  /**
   * @return fatherTelephone
   */
  public String getFatherTelephone() {
    return fatherTelephone;
  }

  /**
   * @param fatherTelephone
   */
  public void setFatherTelephone(String fatherTelephone) {
    this.fatherTelephone = fatherTelephone;
  }

  /**
   * @return fatherCellphone
   */
  public String getFatherCellphone() {
    return fatherCellphone;
  }

  /**
   * @param fatherCellphone
   */
  public void setFatherCellphone(String fatherCellphone) {
    this.fatherCellphone = fatherCellphone;
  }

  /**
   * @return fatherWechatId
   */
  public String getFatherWechatId() {
    return fatherWechatId;
  }

  /**
   * @param fatherWechatId
   */
  public void setFatherWechatId(String fatherWechatId) {
    this.fatherWechatId = fatherWechatId;
  }

  /**
   * @return motherChineseName
   */
  public String getMotherChineseName() {
    return motherChineseName;
  }

  /**
   * @param motherChineseName
   */
  public void setMotherChineseName(String motherChineseName) {
    this.motherChineseName = motherChineseName;
  }

  /**
   * @return motherEnglishName
   */
  public String getMotherEnglishName() {
    return motherEnglishName;
  }

  /**
   * @param motherEnglishName
   */
  public void setMotherEnglishName(String motherEnglishName) {
    this.motherEnglishName = motherEnglishName;
  }

  /**
   * @return motherAddress
   */
  public String getMotherAddress() {
    return motherAddress;
  }

  /**
   * @param motherAddress
   */
  public void setMotherAddress(String motherAddress) {
    this.motherAddress = motherAddress;
  }

  /**
   * @return motherTelephone
   */
  public String getMotherTelephone() {
    return motherTelephone;
  }

  /**
   * @param motherTelephone
   */
  public void setMotherTelephone(String motherTelephone) {
    this.motherTelephone = motherTelephone;
  }

  /**
   * @return motherCellphone
   */
  public String getMotherCellphone() {
    return motherCellphone;
  }

  /**
   * @param motherCellphone
   */
  public void setMotherCellphone(String motherCellphone) {
    this.motherCellphone = motherCellphone;
  }

  /**
   * @return motherWechatId
   */
  public String getMotherWechatId() {
    return motherWechatId;
  }

  /**
   * @param motherWechatId
   */
  public void setMotherWechatId(String motherWechatId) {
    this.motherWechatId = motherWechatId;
  }

  /**
   * @return landlordChineseName
   */
  public String getLandlordChineseName() {
    return landlordChineseName;
  }

  /**
   * @param landlordChineseName
   */
  public void setLandlordChineseName(String landlordChineseName) {
    this.landlordChineseName = landlordChineseName;
  }

  /**
   * @return landlordEnglishName
   */
  public String getLandlordEnglishName() {
    return landlordEnglishName;
  }

  /**
   * @param landlordEnglishName
   */
  public void setLandlordEnglishName(String landlordEnglishName) {
    this.landlordEnglishName = landlordEnglishName;
  }

  /**
   * @return landlordAddress
   */
  public String getLandlordAddress() {
    return landlordAddress;
  }

  /**
   * @param landlordAddress
   */
  public void setLandlordAddress(String landlordAddress) {
    this.landlordAddress = landlordAddress;
  }

  /**
   * @return landlordCity
   */
  public String getLandlordCity() {
    return landlordCity;
  }

  /**
   * @param landlordCity
   */
  public void setLandlordCity(String landlordCity) {
    this.landlordCity = landlordCity;
  }

  /**
   * @return landlordState
   */
  public String getLandlordState() {
    return landlordState;
  }

  /**
   * @param landlordState
   */
  public void setLandlordState(String landlordState) {
    this.landlordState = landlordState;
  }

  /**
   * @return landlordZip
   */
  public String getLandlordZip() {
    return landlordZip;
  }

  /**
   * @param landlordZip
   */
  public void setLandlordZip(String landlordZip) {
    this.landlordZip = landlordZip;
  }

  /**
   * @return landlordTelephone
   */
  public String getLandlordTelephone() {
    return landlordTelephone;
  }

  /**
   * @param landlordTelephone
   */
  public void setLandlordTelephone(String landlordTelephone) {
    this.landlordTelephone = landlordTelephone;
  }

  /**
   * @return landlordCellphone
   */
  public String getLandlordCellphone() {
    return landlordCellphone;
  }

  /**
   * @param landlordCellphone
   */
  public void setLandlordCellphone(String landlordCellphone) {
    this.landlordCellphone = landlordCellphone;
  }

  /**
   * @return landlordWechatId
   */
  public String getLandlordWechatId() {
    return landlordWechatId;
  }

  /**
   * @param landlordWechatId
   */
  public void setLandlordWechatId(String landlordWechatId) {
    this.landlordWechatId = landlordWechatId;
  }

  /**
   * @return roommateChineseName
   */
  public String getRoommateChineseName() {
    return roommateChineseName;
  }

  /**
   * @param roommateChineseName
   */
  public void setRoommateChineseName(String roommateChineseName) {
    this.roommateChineseName = roommateChineseName;
  }

  /**
   * @return roommateEnglishName
   */
  public String getRoommateEnglishName() {
    return roommateEnglishName;
  }

  /**
   * @param roommateEnglishName
   */
  public void setRoommateEnglishName(String roommateEnglishName) {
    this.roommateEnglishName = roommateEnglishName;
  }

  /**
   * @return roommateAddress
   */
  public String getRoommateAddress() {
    return roommateAddress;
  }

  /**
   * @param roommateAddress
   */
  public void setRoommateAddress(String roommateAddress) {
    this.roommateAddress = roommateAddress;
  }

  /**
   * @return roommateCity
   */
  public String getRoommateCity() {
    return roommateCity;
  }

  /**
   * @param roommateCity
   */
  public void setRoommateCity(String roommateCity) {
    this.roommateCity = roommateCity;
  }

  /**
   * @return roommateState
   */
  public String getRoommateState() {
    return roommateState;
  }

  /**
   * @param roommateState
   */
  public void setRoommateState(String roommateState) {
    this.roommateState = roommateState;
  }

  /**
   * @return roommateZip
   */
  public String getRoommateZip() {
    return roommateZip;
  }

  /**
   * @param roommateZip
   */
  public void setRoommateZip(String roommateZip) {
    this.roommateZip = roommateZip;
  }

  /**
   * @return roommateTelephone
   */
  public String getRoommateTelephone() {
    return roommateTelephone;
  }

  /**
   * @param roommateTelephone
   */
  public void setRoommateTelephone(String roommateTelephone) {
    this.roommateTelephone = roommateTelephone;
  }

  /**
   * @return roommateCellphone
   */
  public String getRoommateCellphone() {
    return roommateCellphone;
  }

  /**
   * @param roommateCellphone
   */
  public void setRoommateCellphone(String roommateCellphone) {
    this.roommateCellphone = roommateCellphone;
  }

  /**
   * @return neighborChineseName
   */
  public String getNeighborChineseName() {
    return neighborChineseName;
  }

  /**
   * @param neighborChineseName
   */
  public void setNeighborChineseName(String neighborChineseName) {
    this.neighborChineseName = neighborChineseName;
  }

  /**
   * @return neighborEnglishName
   */
  public String getNeighborEnglishName() {
    return neighborEnglishName;
  }

  /**
   * @param neighborEnglishName
   */
  public void setNeighborEnglishName(String neighborEnglishName) {
    this.neighborEnglishName = neighborEnglishName;
  }

  /**
   * @return neighborAddress
   */
  public String getNeighborAddress() {
    return neighborAddress;
  }

  /**
   * @param neighborAddress
   */
  public void setNeighborAddress(String neighborAddress) {
    this.neighborAddress = neighborAddress;
  }

  /**
   * @return neighborCity
   */
  public String getNeighborCity() {
    return neighborCity;
  }

  /**
   * @param neighborCity
   */
  public void setNeighborCity(String neighborCity) {
    this.neighborCity = neighborCity;
  }

  /**
   * @return neighborState
   */
  public String getNeighborState() {
    return neighborState;
  }

  /**
   * @param neighborState
   */
  public void setNeighborState(String neighborState) {
    this.neighborState = neighborState;
  }

  /**
   * @return neighborZip
   */
  public String getNeighborZip() {
    return neighborZip;
  }

  /**
   * @param neighborZip
   */
  public void setNeighborZip(String neighborZip) {
    this.neighborZip = neighborZip;
  }

  /**
   * @return neighborTelephone
   */
  public String getNeighborTelephone() {
    return neighborTelephone;
  }

  /**
   * @param neighborTelephone
   */
  public void setNeighborTelephone(String neighborTelephone) {
    this.neighborTelephone = neighborTelephone;
  }

  /**
   * @return neighborCellphone
   */
  public String getNeighborCellphone() {
    return neighborCellphone;
  }

  /**
   * @param neighborCellphone
   */
  public void setNeighborCellphone(String neighborCellphone) {
    this.neighborCellphone = neighborCellphone;
  }

  /**
   * @return otherChineseName
   */
  public String getOtherChineseName() {
    return otherChineseName;
  }

  /**
   * @param otherChineseName
   */
  public void setOtherChineseName(String otherChineseName) {
    this.otherChineseName = otherChineseName;
  }

  /**
   * @return otherEnglishName
   */
  public String getOtherEnglishName() {
    return otherEnglishName;
  }

  /**
   * @param otherEnglishName
   */
  public void setOtherEnglishName(String otherEnglishName) {
    this.otherEnglishName = otherEnglishName;
  }

  /**
   * @return otherAddress
   */
  public String getOtherAddress() {
    return otherAddress;
  }

  /**
   * @param otherAddress
   */
  public void setOtherAddress(String otherAddress) {
    this.otherAddress = otherAddress;
  }

  /**
   * @return otherCity
   */
  public String getOtherCity() {
    return otherCity;
  }

  /**
   * @param otherCity
   */
  public void setOtherCity(String otherCity) {
    this.otherCity = otherCity;
  }

  /**
   * @return otherState
   */
  public String getOtherState() {
    return otherState;
  }

  /**
   * @param otherState
   */
  public void setOtherState(String otherState) {
    this.otherState = otherState;
  }

  /**
   * @return otherZip
   */
  public String getOtherZip() {
    return otherZip;
  }

  /**
   * @param otherZip
   */
  public void setOtherZip(String otherZip) {
    this.otherZip = otherZip;
  }

  /**
   * @return otherTelephone
   */
  public String getOtherTelephone() {
    return otherTelephone;
  }

  /**
   * @param otherTelephone
   */
  public void setOtherTelephone(String otherTelephone) {
    this.otherTelephone = otherTelephone;
  }

  /**
   * @return otherCellphone
   */
  public String getOtherCellphone() {
    return otherCellphone;
  }

  /**
   * @param otherCellphone
   */
  public void setOtherCellphone(String otherCellphone) {
    this.otherCellphone = otherCellphone;
  }

  /**
   * @return special
   */
  public Byte getSpecial() {
    return special;
  }

  /**
   * @param special
   */
  public void setSpecial(Byte special) {
    this.special = special;
  }

  /**
   * @return specialComment
   */
  public String getSpecialComment() {
    return specialComment;
  }

  /**
   * @param specialComment
   */
  public void setSpecialComment(String specialComment) {
    this.specialComment = specialComment;
  }

  /**
   * @return total
   */
  public Integer getTotal() {
    return total;
  }

  /**
   * @param total
   */
  public void setTotal(Integer total) {
    this.total = total;
  }

  /**
   * @return used
   */
  public Integer getUsed() {
    return used;
  }

  /**
   * @param used
   */
  public void setUsed(Integer used) {
    this.used = used;
  }

  /**
   * @return expirationDate
   */
  public Date getExpirationDate() {
    return expirationDate;
  }

  /**
   * @param expirationDate
   */
  public void setExpirationDate(Date expirationDate) {
    this.expirationDate = expirationDate;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  /**
   * @return createUserId
   */
  public String getCreateUserId() {
    return createUserId;
  }

  /**
   * @param createUserId
   */
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return updateUserId
   */
  public String getUpdateUserId() {
    return updateUserId;
  }

  /**
   * @param updateUserId
   */
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }

  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

}
