package com.lumei.crm.customer.dto;

import java.io.Serializable;
import java.util.Date;

import com.lumei.crm.commons.biz.support.BaseModel;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Jul 30 23:58:18 CST 2016
 */
public class Notes extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * @field id
   */
  private String id;

  /**
   * @field noteServiceType
   */
  private String noteServiceType;

  /**
   * @field userId
   */
  private String userId;

  /**
   * @field commitUserId
   */
  private String commitUserId;

  /**
   * @field commitTime
   */
  private Date commitTime;

  /**
   * @field content
   */
  private String content;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return noteServiceType
   */
  public String getNoteServiceType() {
    return noteServiceType;
  }

  /**
   * @param noteServiceType
   */
  public void setNoteServiceType(String noteServiceType) {
    this.noteServiceType = noteServiceType;
  }

  /**
   * @return userId
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param userId
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return commitUserId
   */
  public String getCommitUserId() {
    return commitUserId;
  }

  /**
   * @param commitUserId
   */
  public void setCommitUserId(String commitUserId) {
    this.commitUserId = commitUserId;
  }

  /**
   * @return commitTime
   */
  public Date getCommitTime() {
    return commitTime;
  }

  /**
   * @param commitTime
   */
  public void setCommitTime(Date commitTime) {
    this.commitTime = commitTime;
  }

  /**
   * @return content
   */
  public String getContent() {
    return content;
  }

  /**
   * @param content
   */
  public void setContent(String content) {
    this.content = content;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

}
