package com.lumei.crm.customer.dto;

import java.io.Serializable;
import java.util.Date;
// import com.cmbchina.commons.biz.support.BaseModel;
// import org.hibernate.validator.constraints.Length;

import com.lumei.crm.commons.biz.support.BaseModel;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue Aug 02 16:22:53 CST 2016
 */
public class Profile extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * @field id
   */
  private String id;

  /**
   * @field name
   */
  private String name;

  /**
   * @field gender
   */
  private Short gender;

  /**
   * @field phone
   */
  private String phone;

  /**
   * @field email
   */
  private String email;

  /**
   * @field street
   */
  private String street;

  /**
   * @field city
   */
  private String city;

  /**
   * @field state
   */
  private String state;

  /**
   * @field zipCode
   */
  private String zipCode;

  /**
   * @field university
   */
  private String university;

  /**
   * @field status
   */
  private String status;

  /**
   * @field deposit
   */
  private String deposit;

  /**
   * @field whenToBuy
   */
  private String whenToBuy;

  /**
   * @field cashDeal
   */
  private String cashDeal;

  /**
   * @field finance
   */
  private String finance;

  /**
   * @field leasing
   */
  private String leasing;

  /**
   * @field category
   */
  private String category;

  /**
   * @field service
   */
  private String service;

  /**
   * @field effectDate
   */
  private Date effectDate;

  /**
   * @field experiationDate
   */
  private Date experiationDate;

  /**
   * @field totalEvents
   */
  private Integer totalEvents;

  /**
   * @field usedEvents
   */
  private Integer usedEvents;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @field createUserId
   */
  private String createUserId;

  /**
   * @field createTime
   */
  private Date createTime;

  /**
   * @field updateUserId
   */
  private String updateUserId;

  /**
   * @field updateTime
   */
  private Date updateTime;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return name
   */
  public String getName() {
    return name;
  }

  /**
   * @param name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * @return gender
   */
  public Short getGender() {
    return gender;
  }

  /**
   * @param gender
   */
  public void setGender(Short gender) {
    this.gender = gender;
  }

  /**
   * @return phone
   */
  public String getPhone() {
    return phone;
  }

  /**
   * @param phone
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * @return email
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param email
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * @return street
   */
  public String getStreet() {
    return street;
  }

  /**
   * @param street
   */
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   * @return city
   */
  public String getCity() {
    return city;
  }

  /**
   * @param city
   */
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * @return state
   */
  public String getState() {
    return state;
  }

  /**
   * @param state
   */
  public void setState(String state) {
    this.state = state;
  }

  /**
   * @return zipCode
   */
  public String getZipCode() {
    return zipCode;
  }

  /**
   * @param zipCode
   */
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  /**
   * @return university
   */
  public String getUniversity() {
    return university;
  }

  /**
   * @param university
   */
  public void setUniversity(String university) {
    this.university = university;
  }

  /**
   * @return status
   */
  public String getStatus() {
    return status;
  }

  /**
   * @param status
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * @return deposit
   */
  public String getDeposit() {
    return deposit;
  }

  /**
   * @param deposit
   */
  public void setDeposit(String deposit) {
    this.deposit = deposit;
  }

  /**
   * @return whenToBuy
   */
  public String getWhenToBuy() {
    return whenToBuy;
  }

  /**
   * @param whenToBuy
   */
  public void setWhenToBuy(String whenToBuy) {
    this.whenToBuy = whenToBuy;
  }

  /**
   * @return cashDeal
   */
  public String getCashDeal() {
    return cashDeal;
  }

  /**
   * @param cashDeal
   */
  public void setCashDeal(String cashDeal) {
    this.cashDeal = cashDeal;
  }

  /**
   * @return finance
   */
  public String getFinance() {
    return finance;
  }

  /**
   * @param finance
   */
  public void setFinance(String finance) {
    this.finance = finance;
  }

  /**
   * @return leasing
   */
  public String getLeasing() {
    return leasing;
  }

  /**
   * @param leasing
   */
  public void setLeasing(String leasing) {
    this.leasing = leasing;
  }

  /**
   * @return category
   */
  public String getCategory() {
    return category;
  }

  /**
   * @param category
   */
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   * @return service
   */
  public String getService() {
    return service;
  }

  /**
   * @param service
   */
  public void setService(String service) {
    this.service = service;
  }

  /**
   * @return effectDate
   */
  public Date getEffectDate() {
    return effectDate;
  }

  /**
   * @param effectDate
   */
  public void setEffectDate(Date effectDate) {
    this.effectDate = effectDate;
  }

  /**
   * @return experiationDate
   */
  public Date getExperiationDate() {
    return experiationDate;
  }

  /**
   * @param experiationDate
   */
  public void setExperiationDate(Date experiationDate) {
    this.experiationDate = experiationDate;
  }

  /**
   * @return totalEvents
   */
  public Integer getTotalEvents() {
    return totalEvents;
  }

  /**
   * @param totalEvents
   */
  public void setTotalEvents(Integer totalEvents) {
    this.totalEvents = totalEvents;
  }

  /**
   * @return usedEvents
   */
  public Integer getUsedEvents() {
    return usedEvents;
  }

  /**
   * @param usedEvents
   */
  public void setUsedEvents(Integer usedEvents) {
    this.usedEvents = usedEvents;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  /**
   * @return createUserId
   */
  public String getCreateUserId() {
    return createUserId;
  }

  /**
   * @param createUserId
   */
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return updateUserId
   */
  public String getUpdateUserId() {
    return updateUserId;
  }

  /**
   * @param updateUserId
   */
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }

  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

}
