package com.lumei.crm.auth.entity;

import java.util.Date;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue Jun 16 21:06:26 CST 2015
 */
public class TOpAuthUser extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field USER_NAME
   */
  private String userName;

  /**
   * @field PASSWORD
   */
  private String password;

  /**
   * @field SALT
   */
  private String salt;

  /**
   * @field NICK_NAME
   */
  private String nickName;

  /**
   * @field ENABLED
   */
  private Byte enabled;

  /**
   * @field CREATE_BY
   */
  private String createBy;

  /**
   * @field CREATE_TIME
   */
  private Date createTime;

  /**
   * @field UPDATE_BY
   */
  private String updateBy;

  /**
   * @field UPDATE_TIME
   */
  private Date updateTime;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return USER_NAME
   */
  public String getUserName() {
    return userName;
  }

  /**
   * @param USER_NAME
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * @return PASSWORD
   */
  public String getPassword() {
    return password;
  }

  /**
   * @param PASSWORD
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * @return SALT
   */
  public String getSalt() {
    return salt;
  }

  /**
   * @param SALT
   */
  public void setSalt(String salt) {
    this.salt = salt;
  }

  /**
   * @return NICK_NAME
   */
  public String getNickName() {
    return nickName;
  }

  /**
   * @param NICK_NAME
   */
  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  /**
   * @return ENABLED
   */
  public Byte getEnabled() {
    return enabled;
  }

  /**
   * @param ENABLED
   */
  public void setEnabled(Byte enabled) {
    this.enabled = enabled;
  }

  /**
   * @return CREATE_BY
   */
  public String getCreateBy() {
    return createBy;
  }

  /**
   * @param CREATE_BY
   */
  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  /**
   * @return CREATE_TIME
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param CREATE_TIME
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return UPDATE_BY
   */
  public String getUpdateBy() {
    return updateBy;
  }

  /**
   * @param UPDATE_BY
   */
  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  /**
   * @return UPDATE_TIME
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param UPDATE_TIME
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
