package com.lumei.crm.auth.entity;

import java.util.Date;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue Jun 16 21:06:25 CST 2015
 */
public class TOpAuthUserRole extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field USER_ID
   */
  private String userId;

  /**
   * @field ROLE_ID
   */
  private String roleId;

  /**
   * @field ROLE_NAME
   */
  private String roleName;

  /**
   * @field CREATE_BY
   */
  private String createBy;

  /**
   * @field CREATE_TIME
   */
  private Date createTime;

  /**
   * @field UPDATE_BY
   */
  private String updateBy;

  /**
   * @field UPDATE_TIME
   */
  private Date updateTime;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return USER_ID
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param USER_ID
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return ROLE_ID
   */
  public String getRoleId() {
    return roleId;
  }

  /**
   * @param ROLE_ID
   */
  public void setRoleId(String roleId) {
    this.roleId = roleId;
  }

  /**
   * @return ROLE_NAME
   */
  public String getRoleName() {
    return roleName;
  }

  /**
   * @param ROLE_NAME
   */
  public void setRoleName(String roleName) {
    this.roleName = roleName;
  }

  /**
   * @return CREATE_BY
   */
  public String getCreateBy() {
    return createBy;
  }

  /**
   * @param CREATE_BY
   */
  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  /**
   * @return CREATE_TIME
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param CREATE_TIME
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return UPDATE_BY
   */
  public String getUpdateBy() {
    return updateBy;
  }

  /**
   * @param UPDATE_BY
   */
  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  /**
   * @return UPDATE_TIME
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param UPDATE_TIME
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
