package com.lumei.crm.auth.dto;

import java.io.Serializable;
import java.util.Date;

import com.lumei.crm.commons.biz.support.BaseModel;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue Jun 16 21:06:26 CST 2015
 */
public class OpAuthUser extends BaseModel<String> implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * @field id
   */
  private String id;

  /**
   * @field userName
   */
  private String userName;

  /**
   * @field password
   */
  private String password;

  /**
   * @field salt
   */
  private String salt;

  /**
   * @field nickName
   */
  private String nickName;

  /**
   * @field enabled
   */
  private Byte enabled;

  /**
   * @field createBy
   */
  private String createBy;

  /**
   * @field createTime
   */
  private Date createTime;

  /**
   * @field updateBy
   */
  private String updateBy;

  /**
   * @field updateTime
   */
  private Date updateTime;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return userName
   */
  public String getUserName() {
    return userName;
  }

  /**
   * @param userName
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * @return password
   */
  public String getPassword() {
    return password;
  }

  /**
   * @param password
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * @return salt
   */
  public String getSalt() {
    return salt;
  }

  /**
   * @param salt
   */
  public void setSalt(String salt) {
    this.salt = salt;
  }

  /**
   * @return nickName
   */
  public String getNickName() {
    return nickName;
  }

  /**
   * @param nickName
   */
  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  /**
   * @return enabled
   */
  public Byte getEnabled() {
    return enabled;
  }

  /**
   * @param enabled
   */
  public void setEnabled(Byte enabled) {
    this.enabled = enabled;
  }

  /**
   * @return createBy
   */
  public String getCreateBy() {
    return createBy;
  }

  /**
   * @param createBy
   */
  public void setCreateBy(String createBy) {
    this.createBy = createBy;
  }

  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return updateBy
   */
  public String getUpdateBy() {
    return updateBy;
  }

  /**
   * @param updateBy
   */
  public void setUpdateBy(String updateBy) {
    this.updateBy = updateBy;
  }

  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

}
