package com.lumei.crm.customer.service.impl;

import com.lumei.crm.customer.biz.CarBuyingBusiness;
import com.lumei.crm.customer.service.ICarBuyingService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * 
 * @generated by Code Generator v0.1
 * @Sat Jul 30 23:58:18 CST 2016
 */
public class CarBuyingServiceImpl implements ICarBuyingService {

  @Autowired
  private CarBuyingBusiness carBuyingBusiness;

  private static Logger logger = LoggerFactory.getLogger(CarBuyingServiceImpl.class);

}
