package com.lumei.crm.customer.service.impl;

import com.lumei.crm.customer.biz.NotesBusiness;
import com.lumei.crm.customer.service.INotesService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * 
 * @generated by Code Generator v0.1
 * @Sat Jul 30 23:58:18 CST 2016
 */
public class NotesServiceImpl implements INotesService {

  @Autowired
  private NotesBusiness notesBusiness;

  private static Logger logger = LoggerFactory.getLogger(NotesServiceImpl.class);

}
