package com.lumei.crm.customer.service.impl;

import com.lumei.crm.customer.biz.ProfileBusiness;
import com.lumei.crm.customer.service.IProfileService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * 
 * @generated by Code Generator v0.1
 * @Sat Jul 30 23:58:18 CST 2016
 */
public class ProfileServiceImpl implements IProfileService {

  @Autowired
  private ProfileBusiness profileBusiness;

  private static Logger logger = LoggerFactory.getLogger(ProfileServiceImpl.class);

}
