package com.lumei.crm.auth.dao;

import com.lumei.crm.auth.entity.TOpAuthUserRole;
import com.lumei.crm.commons.dao.support.BaseDao;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Fri Jun 12 18:44:36 CST 2015
 */
public interface OpAuthUserRoleDao extends BaseDao<TOpAuthUserRole> {

}
