package com.lumei.crm.customer.dao;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.customer.entity.TCarDeal;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 13 20:32:59 CST 2016
 */
public interface CarDealDao extends BaseDao<TCarDeal> {

  public List<TCarDeal> selectForList(Map param);
  
  public List<TCarDeal> selectForList(String name, String phone, String wechat,
      Byte rating, Byte dealStatus, Date dealDateStart, Date dealDateEnd,
      int page, int limit);


  public Integer countForList(Map param);

  public Integer countForList(String name, String phone, String wechat,
    Byte rating, Byte dealStatus, Date dealDateStart, Date dealDateEnd,
    int page, int limit);
}
