package com.lumei.crm.customer.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.RowBounds;

import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.customer.entity.TCarDeal;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 13 20:32:59 CST 2016
 */
public interface CarDealDao extends BaseDao<TCarDeal> {

  public List<TCarDeal> selectForList(Map param);
  public List<TCarDeal> selectForList(Map param, RowBounds rowBounds);
  public Integer countForList(Map param);
  
}
