package com.lumei.crm.customer.dao;

import com.lumei.crm.customer.entity.TCarInsurance;
import com.lumei.crm.commons.dao.support.BaseDao;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sun Aug 28 13:20:17 CST 2016
 */
public interface CarInsuranceDao extends BaseDao<TCarInsurance> {

}
