package com.lumei.crm.customer.dao;

import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.customer.entity.TEmergencyContact;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 06 12:01:34 CST 2016
 */
public interface EmergencyContactDao extends BaseDao<TEmergencyContact> {

}
