package com.lumei.crm.customer.dao;

import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.customer.entity.TSequence;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 20 11:58:51 CST 2016
 */
public interface SequenceDao extends BaseDao<TSequence> {

}
