package com.lumei.crm.customer.dao;

import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.customer.entity.TServiceLog;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sun Aug 07 05:35:39 CST 2016
 */
public interface ServiceLogDao extends BaseDao<TServiceLog> {

}
