package com.lumei.crm.customer.dao;

import com.lumei.crm.commons.dao.support.BaseDao;
import com.lumei.crm.customer.entity.TTransaction;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 13 20:39:29 CST 2016
 */
public interface TransactionDao extends BaseDao<TTransaction> {

}
