package com.lumei.crm.customer.entity;

import java.util.Date;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 13 20:32:59 CST 2016
 */
public class TCarDeal extends BaseEntity<String> {

  
  private String customerName;

  private String wechat;

  private String phone;
  
  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public String getWechat() {
    return wechat;
  }

  public void setWechat(String wechat) {
    this.wechat = wechat;
  }

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * @field id
   */
  private String id;

  /**
   * @field customerId
   */
  private String customerId;

  /**
   * @field salesId
   */
  private String salesId;

  /**
   * @field dealStatus
   */
  private Byte dealStatus;

  /**
   * @field dealDate
   */
  private Date dealDate;

  /**
   * @field rating
   */
  private Byte rating;

  /**
   * @field deposit
   */
  private Byte deposit;

  /**
   * @field creditCardNo
   */
  private String creditCardNo;

  /**
   * @field isNew
   */
  private Byte isNew;
  
  private Byte source;
  
  private String mileages;
  
  private String tradeIn;
  
  private String caseNo;

  /**
   * @field years
   */
  private String years;

  /**
   * @field makes
   */
  private String makes;

  /**
   * @field model
   */
  private String model;

  /**
   * @field exteriorColor
   */
  private String exteriorColor;

  /**
   * @field interiorColor
   */
  private String interiorColor;

  /**
   * @field msrp
   */
  private String msrp;

  /**
   * @field sellingPrice
   */
  private String sellingPrice;

  /**
   * @field comments
   */
  private String comments;

  /**
   * @field method
   */
  private Byte method;

  /**
   * @field downPayment
   */
  private String downPayment;

  /**
   * @field rate
   */
  private String rate;

  /**
   * @field terms
   */
  private String terms;

  /**
   * @field monthlyPay
   */
  private String monthlyPay;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @field createUserId
   */
  private String createUserId;

  /**
   * @field createTime
   */
  private Date createTime;

  /**
   * @field updateUserId
   */
  private String updateUserId;

  /**
   * @field updateTime
   */
  private Date updateTime;

  /**
   * @field AMBASSADOR
   */
  private String ambassador;

  /**
   * @field TRADE_IN_VALUE
   */
  private String tradeInValue;

  /**
   * @field TRADE_IN_MAKE
   */
  private String tradeInMake;

  /**
   * @field TRADE_IN_MODEL
   */
  private String tradeInModel;

  /**
   * @field TRADE_IN_YEAR
   */
  private String tradeInYear;

  /**
   * @field TRADE_IN_MILEAGE
   */
  private String tradeInMileage;

  /**
   * @field TRADE_IN_EC
   */
  private String tradeInEc;

  /**
   * @field TRADE_IN_IC
   */
  private String tradeInIc;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return customerId
   */
  public String getCustomerId() {
    return customerId;
  }

  /**
   * @param customerId
   */
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  /**
   * @return salesId
   */
  public String getSalesId() {
    return salesId;
  }

  /**
   * @param salesId
   */
  public void setSalesId(String salesId) {
    this.salesId = salesId;
  }

  /**
   * @return dealStatus
   */
  public Byte getDealStatus() {
    return dealStatus;
  }

  /**
   * @param dealStatus
   */
  public void setDealStatus(Byte dealStatus) {
    this.dealStatus = dealStatus;
  }

  /**
   * @return dealDate
   */
  public Date getDealDate() {
    return dealDate;
  }

  /**
   * @param dealDate
   */
  public void setDealDate(Date dealDate) {
    this.dealDate = dealDate;
  }

  /**
   * @return rating
   */
  public Byte getRating() {
    return rating;
  }

  /**
   * @param rating
   */
  public void setRating(Byte rating) {
    this.rating = rating;
  }

  /**
   * @return deposit
   */
  public Byte getDeposit() {
    return deposit;
  }

  /**
   * @param deposit
   */
  public void setDeposit(Byte deposit) {
    this.deposit = deposit;
  }

  /**
   * @return creditCardNo
   */
  public String getCreditCardNo() {
    return creditCardNo;
  }

  /**
   * @param creditCardNo
   */
  public void setCreditCardNo(String creditCardNo) {
    this.creditCardNo = creditCardNo;
  }

  /**
   * @return isNew
   */
  public Byte getIsNew() {
    return isNew;
  }

  /**
   * @param isNew
   */
  public void setIsNew(Byte isNew) {
    this.isNew = isNew;
  }

  public Byte getSource() {
    return source;
  }

  public void setSource(Byte source) {
    this.source = source;
  }

  public String getMileages() {
    return mileages;
  }

  public void setMileages(String mileages) {
    this.mileages = mileages;
  }

  public String getTradeIn() {
    return tradeIn;
  }

  public void setTradeIn(String tradeIn) {
    this.tradeIn = tradeIn;
  }

  public String getCaseNo() {
    return caseNo;
  }

  public void setCaseNo(String caseNo) {
    this.caseNo = caseNo;
  }

  /**
   * @return years
   */
  public String getYears() {
    return years;
  }

  /**
   * @param years
   */
  public void setYears(String years) {
    this.years = years;
  }

  /**
   * @return makes
   */
  public String getMakes() {
    return makes;
  }

  /**
   * @param makes
   */
  public void setMakes(String makes) {
    this.makes = makes;
  }

  /**
   * @return model
   */
  public String getModel() {
    return model;
  }

  /**
   * @param model
   */
  public void setModel(String model) {
    this.model = model;
  }

  /**
   * @return exteriorColor
   */
  public String getExteriorColor() {
    return exteriorColor;
  }

  /**
   * @param exteriorColor
   */
  public void setExteriorColor(String exteriorColor) {
    this.exteriorColor = exteriorColor;
  }

  /**
   * @return interiorColor
   */
  public String getInteriorColor() {
    return interiorColor;
  }

  /**
   * @param interiorColor
   */
  public void setInteriorColor(String interiorColor) {
    this.interiorColor = interiorColor;
  }

  /**
   * @return msrp
   */
  public String getMsrp() {
    return msrp;
  }

  /**
   * @param msrp
   */
  public void setMsrp(String msrp) {
    this.msrp = msrp;
  }

  /**
   * @return sellingPrice
   */
  public String getSellingPrice() {
    return sellingPrice;
  }

  /**
   * @param sellingPrice
   */
  public void setSellingPrice(String sellingPrice) {
    this.sellingPrice = sellingPrice;
  }

  /**
   * @return comments
   */
  public String getComments() {
    return comments;
  }

  /**
   * @param comments
   */
  public void setComments(String comments) {
    this.comments = comments;
  }

  /**
   * @return method
   */
  public Byte getMethod() {
    return method;
  }

  /**
   * @param method
   */
  public void setMethod(Byte method) {
    this.method = method;
  }

  /**
   * @return downPayment
   */
  public String getDownPayment() {
    return downPayment;
  }

  /**
   * @param downPayment
   */
  public void setDownPayment(String downPayment) {
    this.downPayment = downPayment;
  }

  /**
   * @return rate
   */
  public String getRate() {
    return rate;
  }

  /**
   * @param rate
   */
  public void setRate(String rate) {
    this.rate = rate;
  }

  /**
   * @return terms
   */
  public String getTerms() {
    return terms;
  }

  /**
   * @param terms
   */
  public void setTerms(String terms) {
    this.terms = terms;
  }

  /**
   * @return monthlyPay
   */
  public String getMonthlyPay() {
    return monthlyPay;
  }

  /**
   * @param monthlyPay
   */
  public void setMonthlyPay(String monthlyPay) {
    this.monthlyPay = monthlyPay;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  /**
   * @return createUserId
   */
  public String getCreateUserId() {
    return createUserId;
  }

  /**
   * @param createUserId
   */
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return updateUserId
   */
  public String getUpdateUserId() {
    return updateUserId;
  }

  /**
   * @param updateUserId
   */
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }

  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * @return AMBASSADOR
   */
  public String getAmbassador() {
    return ambassador;
  }

  /**
   * @param AMBASSADOR
   */
  public void setAmbassador(String ambassador) {
    this.ambassador = ambassador;
  }

  /**
   * @return TRADE_IN_VALUE
   */
  public String getTradeInValue() {
    return tradeInValue;
  }

  /**
   * @param TRADE_IN_VALUE
   */
  public void setTradeInValue(String tradeInValue) {
    this.tradeInValue = tradeInValue;
  }

  /**
   * @return TRADE_IN_MAKE
   */
  public String getTradeInMake() {
    return tradeInMake;
  }

  /**
   * @param TRADE_IN_MAKE
   */
  public void setTradeInMake(String tradeInMake) {
    this.tradeInMake = tradeInMake;
  }

  /**
   * @return TRADE_IN_MODEL
   */
  public String getTradeInModel() {
    return tradeInModel;
  }

  /**
   * @param TRADE_IN_MODEL
   */
  public void setTradeInModel(String tradeInModel) {
    this.tradeInModel = tradeInModel;
  }

  /**
   * @return TRADE_IN_YEAR
   */
  public String getTradeInYear() {
    return tradeInYear;
  }

  /**
   * @param TRADE_IN_YEAR
   */
  public void setTradeInYear(String tradeInYear) {
    this.tradeInYear = tradeInYear;
  }

  /**
   * @return TRADE_IN_MILEAGE
   */
  public String getTradeInMileage() {
    return tradeInMileage;
  }

  /**
   * @param TRADE_IN_MILEAGE
   */
  public void setTradeInMileage(String tradeInMileage) {
    this.tradeInMileage = tradeInMileage;
  }

  /**
   * @return TRADE_IN_EC
   */
  public String getTradeInEc() {
    return tradeInEc;
  }

  /**
   * @param TRADE_IN_EC
   */
  public void setTradeInEc(String tradeInEc) {
    this.tradeInEc = tradeInEc;
  }

  /**
   * @return TRADE_IN_IC
   */
  public String getTradeInIc() {
    return tradeInIc;
  }

  /**
   * @param TRADE_IN_IC
   */
  public void setTradeInIc(String tradeInIc) {
    this.tradeInIc = tradeInIc;
  }

}
