package com.lumei.crm.customer.entity;

import java.util.Date;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Tue Aug 02 16:22:53 CST 2016
 */
public class TCarBuying extends BaseEntity<String> {

  /**
   * @field id
   */
  private String id;

  /**
   * @field userId
   */
  private String userId;

  /**
   * @field salesName
   */
  private String salesName;

  /**
   * @field category
   */
  private String category;

  /**
   * @field carDescription
   */
  private String carDescription;

  /**
   * @field makes
   */
  private String makes;

  /**
   * @field model
   */
  private String model;

  /**
   * @field isNew
   */
  private Short isNew;

  /**
   * @field years
   */
  private String years;

  /**
   * @field mileages
   */
  private String mileages;

  /**
   * @field msrp
   */
  private String msrp;

  /**
   * @field color
   */
  private String color;

  /**
   * @field exterior
   */
  private String exterior;

  /**
   * @field interior
   */
  private String interior;

  /**
   * @field comments
   */
  private String comments;

  /**
   * @field additionalInformation
   */
  private String additionalInformation;

  /**
   * @field creditCardNo
   */
  private String creditCardNo;

  /**
   * @field expirationDate
   */
  private String expirationDate;

  /**
   * @field cvs
   */
  private String cvs;

  /**
   * @field driversLicense
   */
  private String driversLicense;

  /**
   * @field financeDownPayment
   */
  private String financeDownPayment;

  /**
   * @field financeRate
   */
  private String financeRate;

  /**
   * @field financeTerms
   */
  private String financeTerms;

  /**
   * @field financeMonthlyPay
   */
  private String financeMonthlyPay;

  /**
   * @field financeComments
   */
  private String financeComments;

  /**
   * @field leaseAdditionalFile
   */
  private String leaseAdditionalFile;

  /**
   * @field leaseDownPayment
   */
  private String leaseDownPayment;

  /**
   * @field leaseTerms
   */
  private String leaseTerms;

  /**
   * @field leaseMonthlyPay
   */
  private String leaseMonthlyPay;

  /**
   * @field leaseComments
   */
  private String leaseComments;

  /**
   * @field tradeIn
   */
  private String tradeIn;

  /**
   * @field tradeInMakes
   */
  private String tradeInMakes;

  /**
   * @field tradeInModel
   */
  private String tradeInModel;

  /**
   * @field tradeInYears
   */
  private String tradeInYears;

  /**
   * @field tradeInMileage
   */
  private String tradeInMileage;

  /**
   * @field tradeInValue
   */
  private String tradeInValue;

  /**
   * @field tradeInColor
   */
  private String tradeInColor;

  /**
   * @field tradeInExterior
   */
  private String tradeInExterior;

  /**
   * @field tradeInInterior
   */
  private String tradeInInterior;

  /**
   * @field notes
   */
  private String notes;

  /**
   * @field deleteFlag
   */
  private Byte deleteFlag;

  /**
   * @field createUserId
   */
  private String createUserId;

  /**
   * @field createTime
   */
  private Date createTime;

  /**
   * @field updateUserId
   */
  private String updateUserId;

  /**
   * @field updateTime
   */
  private Date updateTime;

  /**
   * @return id
   */
  public String getId() {
    return id;
  }

  /**
   * @param id
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return userId
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param userId
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return salesName
   */
  public String getSalesName() {
    return salesName;
  }

  /**
   * @param salesName
   */
  public void setSalesName(String salesName) {
    this.salesName = salesName;
  }

  /**
   * @return category
   */
  public String getCategory() {
    return category;
  }

  /**
   * @param category
   */
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   * @return carDescription
   */
  public String getCarDescription() {
    return carDescription;
  }

  /**
   * @param carDescription
   */
  public void setCarDescription(String carDescription) {
    this.carDescription = carDescription;
  }

  /**
   * @return makes
   */
  public String getMakes() {
    return makes;
  }

  /**
   * @param makes
   */
  public void setMakes(String makes) {
    this.makes = makes;
  }

  /**
   * @return model
   */
  public String getModel() {
    return model;
  }

  /**
   * @param model
   */
  public void setModel(String model) {
    this.model = model;
  }

  /**
   * @return isNew
   */
  public Short getIsNew() {
    return isNew;
  }

  /**
   * @param isNew
   */
  public void setIsNew(Short isNew) {
    this.isNew = isNew;
  }

  /**
   * @return years
   */
  public String getYears() {
    return years;
  }

  /**
   * @param years
   */
  public void setYears(String years) {
    this.years = years;
  }

  /**
   * @return mileages
   */
  public String getMileages() {
    return mileages;
  }

  /**
   * @param mileages
   */
  public void setMileages(String mileages) {
    this.mileages = mileages;
  }

  /**
   * @return msrp
   */
  public String getMsrp() {
    return msrp;
  }

  /**
   * @param msrp
   */
  public void setMsrp(String msrp) {
    this.msrp = msrp;
  }

  /**
   * @return color
   */
  public String getColor() {
    return color;
  }

  /**
   * @param color
   */
  public void setColor(String color) {
    this.color = color;
  }

  /**
   * @return exterior
   */
  public String getExterior() {
    return exterior;
  }

  /**
   * @param exterior
   */
  public void setExterior(String exterior) {
    this.exterior = exterior;
  }

  /**
   * @return interior
   */
  public String getInterior() {
    return interior;
  }

  /**
   * @param interior
   */
  public void setInterior(String interior) {
    this.interior = interior;
  }

  /**
   * @return comments
   */
  public String getComments() {
    return comments;
  }

  /**
   * @param comments
   */
  public void setComments(String comments) {
    this.comments = comments;
  }

  /**
   * @return additionalInformation
   */
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  /**
   * @param additionalInformation
   */
  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  /**
   * @return creditCardNo
   */
  public String getCreditCardNo() {
    return creditCardNo;
  }

  /**
   * @param creditCardNo
   */
  public void setCreditCardNo(String creditCardNo) {
    this.creditCardNo = creditCardNo;
  }

  /**
   * @return expirationDate
   */
  public String getExpirationDate() {
    return expirationDate;
  }

  /**
   * @param expirationDate
   */
  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  /**
   * @return cvs
   */
  public String getCvs() {
    return cvs;
  }

  /**
   * @param cvs
   */
  public void setCvs(String cvs) {
    this.cvs = cvs;
  }

  /**
   * @return driversLicense
   */
  public String getDriversLicense() {
    return driversLicense;
  }

  /**
   * @param driversLicense
   */
  public void setDriversLicense(String driversLicense) {
    this.driversLicense = driversLicense;
  }

  /**
   * @return financeDownPayment
   */
  public String getFinanceDownPayment() {
    return financeDownPayment;
  }

  /**
   * @param financeDownPayment
   */
  public void setFinanceDownPayment(String financeDownPayment) {
    this.financeDownPayment = financeDownPayment;
  }

  /**
   * @return financeRate
   */
  public String getFinanceRate() {
    return financeRate;
  }

  /**
   * @param financeRate
   */
  public void setFinanceRate(String financeRate) {
    this.financeRate = financeRate;
  }

  /**
   * @return financeTerms
   */
  public String getFinanceTerms() {
    return financeTerms;
  }

  /**
   * @param financeTerms
   */
  public void setFinanceTerms(String financeTerms) {
    this.financeTerms = financeTerms;
  }

  /**
   * @return financeMonthlyPay
   */
  public String getFinanceMonthlyPay() {
    return financeMonthlyPay;
  }

  /**
   * @param financeMonthlyPay
   */
  public void setFinanceMonthlyPay(String financeMonthlyPay) {
    this.financeMonthlyPay = financeMonthlyPay;
  }

  /**
   * @return financeComments
   */
  public String getFinanceComments() {
    return financeComments;
  }

  /**
   * @param financeComments
   */
  public void setFinanceComments(String financeComments) {
    this.financeComments = financeComments;
  }

  /**
   * @return leaseAdditionalFile
   */
  public String getLeaseAdditionalFile() {
    return leaseAdditionalFile;
  }

  /**
   * @param leaseAdditionalFile
   */
  public void setLeaseAdditionalFile(String leaseAdditionalFile) {
    this.leaseAdditionalFile = leaseAdditionalFile;
  }

  /**
   * @return leaseDownPayment
   */
  public String getLeaseDownPayment() {
    return leaseDownPayment;
  }

  /**
   * @param leaseDownPayment
   */
  public void setLeaseDownPayment(String leaseDownPayment) {
    this.leaseDownPayment = leaseDownPayment;
  }

  /**
   * @return leaseTerms
   */
  public String getLeaseTerms() {
    return leaseTerms;
  }

  /**
   * @param leaseTerms
   */
  public void setLeaseTerms(String leaseTerms) {
    this.leaseTerms = leaseTerms;
  }

  /**
   * @return leaseMonthlyPay
   */
  public String getLeaseMonthlyPay() {
    return leaseMonthlyPay;
  }

  /**
   * @param leaseMonthlyPay
   */
  public void setLeaseMonthlyPay(String leaseMonthlyPay) {
    this.leaseMonthlyPay = leaseMonthlyPay;
  }

  /**
   * @return leaseComments
   */
  public String getLeaseComments() {
    return leaseComments;
  }

  /**
   * @param leaseComments
   */
  public void setLeaseComments(String leaseComments) {
    this.leaseComments = leaseComments;
  }

  /**
   * @return tradeIn
   */
  public String getTradeIn() {
    return tradeIn;
  }

  /**
   * @param tradeIn
   */
  public void setTradeIn(String tradeIn) {
    this.tradeIn = tradeIn;
  }

  /**
   * @return tradeInMakes
   */
  public String getTradeInMakes() {
    return tradeInMakes;
  }

  /**
   * @param tradeInMakes
   */
  public void setTradeInMakes(String tradeInMakes) {
    this.tradeInMakes = tradeInMakes;
  }

  /**
   * @return tradeInModel
   */
  public String getTradeInModel() {
    return tradeInModel;
  }

  /**
   * @param tradeInModel
   */
  public void setTradeInModel(String tradeInModel) {
    this.tradeInModel = tradeInModel;
  }

  /**
   * @return tradeInYears
   */
  public String getTradeInYears() {
    return tradeInYears;
  }

  /**
   * @param tradeInYears
   */
  public void setTradeInYears(String tradeInYears) {
    this.tradeInYears = tradeInYears;
  }

  /**
   * @return tradeInMileage
   */
  public String getTradeInMileage() {
    return tradeInMileage;
  }

  /**
   * @param tradeInMileage
   */
  public void setTradeInMileage(String tradeInMileage) {
    this.tradeInMileage = tradeInMileage;
  }

  /**
   * @return tradeInValue
   */
  public String getTradeInValue() {
    return tradeInValue;
  }

  /**
   * @param tradeInValue
   */
  public void setTradeInValue(String tradeInValue) {
    this.tradeInValue = tradeInValue;
  }

  /**
   * @return tradeInColor
   */
  public String getTradeInColor() {
    return tradeInColor;
  }

  /**
   * @param tradeInColor
   */
  public void setTradeInColor(String tradeInColor) {
    this.tradeInColor = tradeInColor;
  }

  /**
   * @return tradeInExterior
   */
  public String getTradeInExterior() {
    return tradeInExterior;
  }

  /**
   * @param tradeInExterior
   */
  public void setTradeInExterior(String tradeInExterior) {
    this.tradeInExterior = tradeInExterior;
  }

  /**
   * @return tradeInInterior
   */
  public String getTradeInInterior() {
    return tradeInInterior;
  }

  /**
   * @param tradeInInterior
   */
  public void setTradeInInterior(String tradeInInterior) {
    this.tradeInInterior = tradeInInterior;
  }

  /**
   * @return notes
   */
  public String getNotes() {
    return notes;
  }

  /**
   * @param notes
   */
  public void setNotes(String notes) {
    this.notes = notes;
  }

  /**
   * @return deleteFlag
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param deleteFlag
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  /**
   * @return createUserId
   */
  public String getCreateUserId() {
    return createUserId;
  }

  /**
   * @param createUserId
   */
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return updateUserId
   */
  public String getUpdateUserId() {
    return updateUserId;
  }

  /**
   * @param updateUserId
   */
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }

  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
}
