package com.lumei.crm.customer.entity;

import java.util.Date;
import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sun Aug 28 13:20:17 CST 2016
 */
public class TCarInsurance extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field CUSTOMER_ID
   */
  private String customerId;

  /**
   * @field SALES_ID
   */
  private String salesId;

  /**
   * @field CAR_DEAL_ID
   */
  private String carDealId;

  /**
   * @field STATUS
   */
  private Byte status;

  /**
   * @field EFFECTIVE_DATE
   */
  private Date effectiveDate;

  /**
   * @field CREDIT_CARD_NO
   */
  private String creditCardNo;

  /**
   * @field INSURANCE_COMPANY
   */
  private String insuranceCompany;

  /**
   * @field TERMS
   */
  private String terms;

  /**
   * @field VIN_NO
   */
  private String vinNo;

  /**
   * @field PRICE
   */
  private String price;

  /**
   * @field CASE_NO
   */
  private String caseNo;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @field CREATE_USER_ID
   */
  private String createUserId;

  /**
   * @field CREATE_TIME
   */
  private Date createTime;

  /**
   * @field UPDATE_USER_ID
   */
  private String updateUserId;

  /**
   * @field UPDATE_TIME
   */
  private Date updateTime;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return CUSTOMER_ID
   */
  public String getCustomerId() {
    return customerId;
  }

  /**
   * @param CUSTOMER_ID
   */
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  /**
   * @return SALES_ID
   */
  public String getSalesId() {
    return salesId;
  }

  /**
   * @param SALES_ID
   */
  public void setSalesId(String salesId) {
    this.salesId = salesId;
  }

  /**
   * @return CAR_DEAL_ID
   */
  public String getCarDealId() {
    return carDealId;
  }

  /**
   * @param CAR_DEAL_ID
   */
  public void setCarDealId(String carDealId) {
    this.carDealId = carDealId;
  }

  /**
   * @return STATUS
   */
  public Byte getStatus() {
    return status;
  }

  /**
   * @param STATUS
   */
  public void setStatus(Byte status) {
    this.status = status;
  }

  /**
   * @return EFFECTIVE_DATE
   */
  public Date getEffectiveDate() {
    return effectiveDate;
  }

  /**
   * @param EFFECTIVE_DATE
   */
  public void setEffectiveDate(Date effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  /**
   * @return CREDIT_CARD_NO
   */
  public String getCreditCardNo() {
    return creditCardNo;
  }

  /**
   * @param CREDIT_CARD_NO
   */
  public void setCreditCardNo(String creditCardNo) {
    this.creditCardNo = creditCardNo;
  }

  /**
   * @return INSURANCE_COMPANY
   */
  public String getInsuranceCompany() {
    return insuranceCompany;
  }

  /**
   * @param INSURANCE_COMPANY
   */
  public void setInsuranceCompany(String insuranceCompany) {
    this.insuranceCompany = insuranceCompany;
  }

  /**
   * @return TERMS
   */
  public String getTerms() {
    return terms;
  }

  /**
   * @param TERMS
   */
  public void setTerms(String terms) {
    this.terms = terms;
  }

  /**
   * @return VIN_NO
   */
  public String getVinNo() {
    return vinNo;
  }

  /**
   * @param VIN_NO
   */
  public void setVinNo(String vinNo) {
    this.vinNo = vinNo;
  }

  /**
   * @return PRICE
   */
  public String getPrice() {
    return price;
  }

  /**
   * @param PRICE
   */
  public void setPrice(String price) {
    this.price = price;
  }

  /**
   * @return CASE_NO
   */
  public String getCaseNo() {
    return caseNo;
  }

  /**
   * @param CASE_NO
   */
  public void setCaseNo(String caseNo) {
    this.caseNo = caseNo;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }

  /**
   * @return CREATE_USER_ID
   */
  public String getCreateUserId() {
    return createUserId;
  }

  /**
   * @param CREATE_USER_ID
   */
  public void setCreateUserId(String createUserId) {
    this.createUserId = createUserId;
  }

  /**
   * @return CREATE_TIME
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * @param CREATE_TIME
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * @return UPDATE_USER_ID
   */
  public String getUpdateUserId() {
    return updateUserId;
  }

  /**
   * @param UPDATE_USER_ID
   */
  public void setUpdateUserId(String updateUserId) {
    this.updateUserId = updateUserId;
  }

  /**
   * @return UPDATE_TIME
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * @param UPDATE_TIME
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
}
