package com.lumei.crm.customer.entity;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Jul 30 23:58:18 CST 2016
 */
public class TCarBuying extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field USER_ID
   */
  private String userId;

  /**
   * @field SALES_NAME
   */
  private String salesName;

  /**
   * @field CATEGORY
   */
  private String category;

  /**
   * @field CAR_DESCRIPTION
   */
  private String carDescription;

  /**
   * @field MAKES
   */
  private String makes;

  /**
   * @field MODEL
   */
  private String model;

  /**
   * @field IS_NEW
   */
  private Short isNew;

  /**
   * @field YEARS
   */
  private String years;

  /**
   * @field MILEAGES
   */
  private String mileages;

  /**
   * @field MSRP
   */
  private String msrp;

  /**
   * @field COLOR
   */
  private String color;

  /**
   * @field EXTERIOR
   */
  private String exterior;

  /**
   * @field INTERIOR
   */
  private String interior;

  /**
   * @field COMMENTS
   */
  private String comments;

  /**
   * @field ADDITIONAL_INFORMATION
   */
  private String additionalInformation;

  /**
   * @field CREDIT_CARD_NO
   */
  private String creditCardNo;

  /**
   * @field EXPIRATION_DATE
   */
  private String expirationDate;

  /**
   * @field CVS
   */
  private String cvs;

  /**
   * @field DRIVERS_LICENSE
   */
  private String driversLicense;

  /**
   * @field FINANCE_DOWN_PAYMENT
   */
  private String financeDownPayment;

  /**
   * @field FINANCE_RATE
   */
  private String financeRate;

  /**
   * @field FINANCE_TERMS
   */
  private String financeTerms;

  /**
   * @field FINANCE_MONTHLY_PAY
   */
  private String financeMonthlyPay;

  /**
   * @field FINANCE_COMMENTS
   */
  private String financeComments;

  /**
   * @field LEASE_ADDITIONAL_FILE
   */
  private String leaseAdditionalFile;

  /**
   * @field LEASE_DOWN_PAYMENT
   */
  private String leaseDownPayment;

  /**
   * @field LEASE_TERMS
   */
  private String leaseTerms;

  /**
   * @field LEASE_MONTHLY_PAY
   */
  private String leaseMonthlyPay;

  /**
   * @field LEASE_COMMENTS
   */
  private String leaseComments;

  /**
   * @field TRADE_IN
   */
  private String tradeIn;

  /**
   * @field TRADE_IN_MAKES
   */
  private String tradeInMakes;

  /**
   * @field TRADE_IN_MODEL
   */
  private String tradeInModel;

  /**
   * @field TRADE_IN_YEARS
   */
  private String tradeInYears;

  /**
   * @field TRADE_IN_MILEAGE
   */
  private String tradeInMileage;

  /**
   * @field TRADE_IN_VALUE
   */
  private String tradeInValue;

  /**
   * @field TRADE_IN_COLOR
   */
  private String tradeInColor;

  /**
   * @field TRADE_IN_EXTERIOR
   */
  private String tradeInExterior;

  /**
   * @field TRADE_IN_INTERIOR
   */
  private String tradeInInterior;

  /**
   * @field NOTES
   */
  private String notes;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return USER_ID
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param USER_ID
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return SALES_NAME
   */
  public String getSalesName() {
    return salesName;
  }

  /**
   * @param SALES_NAME
   */
  public void setSalesName(String salesName) {
    this.salesName = salesName;
  }

  /**
   * @return CATEGORY
   */
  public String getCategory() {
    return category;
  }

  /**
   * @param CATEGORY
   */
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   * @return CAR_DESCRIPTION
   */
  public String getCarDescription() {
    return carDescription;
  }

  /**
   * @param CAR_DESCRIPTION
   */
  public void setCarDescription(String carDescription) {
    this.carDescription = carDescription;
  }

  /**
   * @return MAKES
   */
  public String getMakes() {
    return makes;
  }

  /**
   * @param MAKES
   */
  public void setMakes(String makes) {
    this.makes = makes;
  }

  /**
   * @return MODEL
   */
  public String getModel() {
    return model;
  }

  /**
   * @param MODEL
   */
  public void setModel(String model) {
    this.model = model;
  }

  /**
   * @return IS_NEW
   */
  public Short getIsNew() {
    return isNew;
  }

  /**
   * @param IS_NEW
   */
  public void setIsNew(Short isNew) {
    this.isNew = isNew;
  }

  /**
   * @return YEARS
   */
  public String getYears() {
    return years;
  }

  /**
   * @param YEARS
   */
  public void setYears(String years) {
    this.years = years;
  }

  /**
   * @return MILEAGES
   */
  public String getMileages() {
    return mileages;
  }

  /**
   * @param MILEAGES
   */
  public void setMileages(String mileages) {
    this.mileages = mileages;
  }

  /**
   * @return MSRP
   */
  public String getMsrp() {
    return msrp;
  }

  /**
   * @param MSRP
   */
  public void setMsrp(String msrp) {
    this.msrp = msrp;
  }

  /**
   * @return COLOR
   */
  public String getColor() {
    return color;
  }

  /**
   * @param COLOR
   */
  public void setColor(String color) {
    this.color = color;
  }

  /**
   * @return EXTERIOR
   */
  public String getExterior() {
    return exterior;
  }

  /**
   * @param EXTERIOR
   */
  public void setExterior(String exterior) {
    this.exterior = exterior;
  }

  /**
   * @return INTERIOR
   */
  public String getInterior() {
    return interior;
  }

  /**
   * @param INTERIOR
   */
  public void setInterior(String interior) {
    this.interior = interior;
  }

  /**
   * @return COMMENTS
   */
  public String getComments() {
    return comments;
  }

  /**
   * @param COMMENTS
   */
  public void setComments(String comments) {
    this.comments = comments;
  }

  /**
   * @return ADDITIONAL_INFORMATION
   */
  public String getAdditionalInformation() {
    return additionalInformation;
  }

  /**
   * @param ADDITIONAL_INFORMATION
   */
  public void setAdditionalInformation(String additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  /**
   * @return CREDIT_CARD_NO
   */
  public String getCreditCardNo() {
    return creditCardNo;
  }

  /**
   * @param CREDIT_CARD_NO
   */
  public void setCreditCardNo(String creditCardNo) {
    this.creditCardNo = creditCardNo;
  }

  /**
   * @return EXPIRATION_DATE
   */
  public String getExpirationDate() {
    return expirationDate;
  }

  /**
   * @param EXPIRATION_DATE
   */
  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  /**
   * @return CVS
   */
  public String getCvs() {
    return cvs;
  }

  /**
   * @param CVS
   */
  public void setCvs(String cvs) {
    this.cvs = cvs;
  }

  /**
   * @return DRIVERS_LICENSE
   */
  public String getDriversLicense() {
    return driversLicense;
  }

  /**
   * @param DRIVERS_LICENSE
   */
  public void setDriversLicense(String driversLicense) {
    this.driversLicense = driversLicense;
  }

  /**
   * @return FINANCE_DOWN_PAYMENT
   */
  public String getFinanceDownPayment() {
    return financeDownPayment;
  }

  /**
   * @param FINANCE_DOWN_PAYMENT
   */
  public void setFinanceDownPayment(String financeDownPayment) {
    this.financeDownPayment = financeDownPayment;
  }

  /**
   * @return FINANCE_RATE
   */
  public String getFinanceRate() {
    return financeRate;
  }

  /**
   * @param FINANCE_RATE
   */
  public void setFinanceRate(String financeRate) {
    this.financeRate = financeRate;
  }

  /**
   * @return FINANCE_TERMS
   */
  public String getFinanceTerms() {
    return financeTerms;
  }

  /**
   * @param FINANCE_TERMS
   */
  public void setFinanceTerms(String financeTerms) {
    this.financeTerms = financeTerms;
  }

  /**
   * @return FINANCE_MONTHLY_PAY
   */
  public String getFinanceMonthlyPay() {
    return financeMonthlyPay;
  }

  /**
   * @param FINANCE_MONTHLY_PAY
   */
  public void setFinanceMonthlyPay(String financeMonthlyPay) {
    this.financeMonthlyPay = financeMonthlyPay;
  }

  /**
   * @return FINANCE_COMMENTS
   */
  public String getFinanceComments() {
    return financeComments;
  }

  /**
   * @param FINANCE_COMMENTS
   */
  public void setFinanceComments(String financeComments) {
    this.financeComments = financeComments;
  }

  /**
   * @return LEASE_ADDITIONAL_FILE
   */
  public String getLeaseAdditionalFile() {
    return leaseAdditionalFile;
  }

  /**
   * @param LEASE_ADDITIONAL_FILE
   */
  public void setLeaseAdditionalFile(String leaseAdditionalFile) {
    this.leaseAdditionalFile = leaseAdditionalFile;
  }

  /**
   * @return LEASE_DOWN_PAYMENT
   */
  public String getLeaseDownPayment() {
    return leaseDownPayment;
  }

  /**
   * @param LEASE_DOWN_PAYMENT
   */
  public void setLeaseDownPayment(String leaseDownPayment) {
    this.leaseDownPayment = leaseDownPayment;
  }

  /**
   * @return LEASE_TERMS
   */
  public String getLeaseTerms() {
    return leaseTerms;
  }

  /**
   * @param LEASE_TERMS
   */
  public void setLeaseTerms(String leaseTerms) {
    this.leaseTerms = leaseTerms;
  }

  /**
   * @return LEASE_MONTHLY_PAY
   */
  public String getLeaseMonthlyPay() {
    return leaseMonthlyPay;
  }

  /**
   * @param LEASE_MONTHLY_PAY
   */
  public void setLeaseMonthlyPay(String leaseMonthlyPay) {
    this.leaseMonthlyPay = leaseMonthlyPay;
  }

  /**
   * @return LEASE_COMMENTS
   */
  public String getLeaseComments() {
    return leaseComments;
  }

  /**
   * @param LEASE_COMMENTS
   */
  public void setLeaseComments(String leaseComments) {
    this.leaseComments = leaseComments;
  }

  /**
   * @return TRADE_IN
   */
  public String getTradeIn() {
    return tradeIn;
  }

  /**
   * @param TRADE_IN
   */
  public void setTradeIn(String tradeIn) {
    this.tradeIn = tradeIn;
  }

  /**
   * @return TRADE_IN_MAKES
   */
  public String getTradeInMakes() {
    return tradeInMakes;
  }

  /**
   * @param TRADE_IN_MAKES
   */
  public void setTradeInMakes(String tradeInMakes) {
    this.tradeInMakes = tradeInMakes;
  }

  /**
   * @return TRADE_IN_MODEL
   */
  public String getTradeInModel() {
    return tradeInModel;
  }

  /**
   * @param TRADE_IN_MODEL
   */
  public void setTradeInModel(String tradeInModel) {
    this.tradeInModel = tradeInModel;
  }

  /**
   * @return TRADE_IN_YEARS
   */
  public String getTradeInYears() {
    return tradeInYears;
  }

  /**
   * @param TRADE_IN_YEARS
   */
  public void setTradeInYears(String tradeInYears) {
    this.tradeInYears = tradeInYears;
  }

  /**
   * @return TRADE_IN_MILEAGE
   */
  public String getTradeInMileage() {
    return tradeInMileage;
  }

  /**
   * @param TRADE_IN_MILEAGE
   */
  public void setTradeInMileage(String tradeInMileage) {
    this.tradeInMileage = tradeInMileage;
  }

  /**
   * @return TRADE_IN_VALUE
   */
  public String getTradeInValue() {
    return tradeInValue;
  }

  /**
   * @param TRADE_IN_VALUE
   */
  public void setTradeInValue(String tradeInValue) {
    this.tradeInValue = tradeInValue;
  }

  /**
   * @return TRADE_IN_COLOR
   */
  public String getTradeInColor() {
    return tradeInColor;
  }

  /**
   * @param TRADE_IN_COLOR
   */
  public void setTradeInColor(String tradeInColor) {
    this.tradeInColor = tradeInColor;
  }

  /**
   * @return TRADE_IN_EXTERIOR
   */
  public String getTradeInExterior() {
    return tradeInExterior;
  }

  /**
   * @param TRADE_IN_EXTERIOR
   */
  public void setTradeInExterior(String tradeInExterior) {
    this.tradeInExterior = tradeInExterior;
  }

  /**
   * @return TRADE_IN_INTERIOR
   */
  public String getTradeInInterior() {
    return tradeInInterior;
  }

  /**
   * @param TRADE_IN_INTERIOR
   */
  public void setTradeInInterior(String tradeInInterior) {
    this.tradeInInterior = tradeInInterior;
  }

  /**
   * @return NOTES
   */
  public String getNotes() {
    return notes;
  }

  /**
   * @param NOTES
   */
  public void setNotes(String notes) {
    this.notes = notes;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
