package com.lumei.crm.customer.entity;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Jul 30 23:58:18 CST 2016
 */
public class TEmergencyContact extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field USER_ID
   */
  private String userId;

  /**
   * @field SALES_NAME
   */
  private String salesName;

  /**
   * @field DOB
   */
  private String dob;

  /**
   * @field CHINESE_ID
   */
  private String chineseId;

  /**
   * @field PASSPORT
   */
  private String passport;

  /**
   * @field UNIVERSITY
   */
  private String university;

  /**
   * @field SCHOOL
   */
  private String school;

  /**
   * @field DEPARTMENT
   */
  private String department;

  /**
   * @field SCHOOL_EMAIL
   */
  private String schoolEmail;

  /**
   * @field PERSONAL_EMAIL
   */
  private String personalEmail;

  /**
   * @field WECHAT_ID
   */
  private String wechatId;

  /**
   * @field CHINESE_HOME_ADDRESS
   */
  private String chineseHomeAddress;

  /**
   * @field CHINESE_HOME_ZIP
   */
  private String chineseHomeZip;

  /**
   * @field CHINESE_HOME_TELEPHONE
   */
  private String chineseHomeTelephone;

  /**
   * @field CHINESE_HOME_CELLPHONE
   */
  private String chineseHomeCellphone;

  /**
   * @field USA_HOME_ADDRESS
   */
  private String usaHomeAddress;

  /**
   * @field USA_HOME_CITY
   */
  private String usaHomeCity;

  /**
   * @field USA_HOME_STATE
   */
  private String usaHomeState;

  /**
   * @field USA_HOME_ZIP
   */
  private String usaHomeZip;

  /**
   * @field USA_HOME_TELEPHONE
   */
  private String usaHomeTelephone;

  /**
   * @field USA_HOME_CELLPHONE
   */
  private String usaHomeCellphone;

  /**
   * @field FATHER_CHINESE_NAME
   */
  private String fatherChineseName;

  /**
   * @field FATHER_ENGLISH_NAME
   */
  private String fatherEnglishName;

  /**
   * @field FATHER_ADDRESS
   */
  private String fatherAddress;

  /**
   * @field FATHER_TELEPHONE
   */
  private String fatherTelephone;

  /**
   * @field FATHER_CELLPHONE
   */
  private String fatherCellphone;

  /**
   * @field FATHER_WECHAT_ID
   */
  private String fatherWechatId;

  /**
   * @field MOTHER_CHINESE_NAME
   */
  private String motherChineseName;

  /**
   * @field MOTHER_ENGLISH_NAME
   */
  private String motherEnglishName;

  /**
   * @field MOTHER_ADDRESS
   */
  private String motherAddress;

  /**
   * @field MOTHER_TELEPHONE
   */
  private String motherTelephone;

  /**
   * @field MOTHER_CELLPHONE
   */
  private String motherCellphone;

  /**
   * @field MOTHER_WECHAT_ID
   */
  private String motherWechatId;

  /**
   * @field LANDLORD_CHINESE_NAME
   */
  private String landlordChineseName;

  /**
   * @field LANDLORD_ENGLISH_NAME
   */
  private String landlordEnglishName;

  /**
   * @field LANDLORD_ADDRESS
   */
  private String landlordAddress;

  /**
   * @field LANDLORD_CITY
   */
  private String landlordCity;

  /**
   * @field LANDLORD_STATE
   */
  private String landlordState;

  /**
   * @field LANDLORD_ZIP
   */
  private String landlordZip;

  /**
   * @field LANDLORD_TELEPHONE
   */
  private String landlordTelephone;

  /**
   * @field LANDLORD_CELLPHONE
   */
  private String landlordCellphone;

  /**
   * @field LANDLORD_WECHAT_ID
   */
  private String landlordWechatId;

  /**
   * @field ROOMMATE_CHINESE_NAME
   */
  private String roommateChineseName;

  /**
   * @field ROOMMATE_ENGLISH_NAME
   */
  private String roommateEnglishName;

  /**
   * @field ROOMMATE_ADDRESS
   */
  private String roommateAddress;

  /**
   * @field ROOMMATE_CITY
   */
  private String roommateCity;

  /**
   * @field ROOMMATE_STATE
   */
  private String roommateState;

  /**
   * @field ROOMMATE_ZIP
   */
  private String roommateZip;

  /**
   * @field ROOMMATE_TELEPHONE
   */
  private String roommateTelephone;

  /**
   * @field ROOMMATE_CELLPHONE
   */
  private String roommateCellphone;

  /**
   * @field NEIGHBOR_CHINESE_NAME
   */
  private String neighborChineseName;

  /**
   * @field NEIGHBOR_ENGLISH_NAME
   */
  private String neighborEnglishName;

  /**
   * @field NEIGHBOR_ADDRESS
   */
  private String neighborAddress;

  /**
   * @field NEIGHBOR_CITY
   */
  private String neighborCity;

  /**
   * @field NEIGHBOR_STATE
   */
  private String neighborState;

  /**
   * @field NEIGHBOR_ZIP
   */
  private String neighborZip;

  /**
   * @field NEIGHBOR_TELEPHONE
   */
  private String neighborTelephone;

  /**
   * @field NEIGHBOR_CELLPHONE
   */
  private String neighborCellphone;

  /**
   * @field OTHER_CHINESE_NAME
   */
  private String otherChineseName;

  /**
   * @field OTHER_ENGLISH_NAME
   */
  private String otherEnglishName;

  /**
   * @field OTHER_ADDRESS
   */
  private String otherAddress;

  /**
   * @field OTHER_CITY
   */
  private String otherCity;

  /**
   * @field OTHER_STATE
   */
  private String otherState;

  /**
   * @field OTHER_ZIP
   */
  private String otherZip;

  /**
   * @field OTHER_TELEPHONE
   */
  private String otherTelephone;

  /**
   * @field OTHER_CELLPHONE
   */
  private String otherCellphone;

  /**
   * @field SPECIAL
   */
  private Byte special;

  /**
   * @field SPECIAL_COMMENT
   */
  private String specialComment;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return USER_ID
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param USER_ID
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return SALES_NAME
   */
  public String getSalesName() {
    return salesName;
  }

  /**
   * @param SALES_NAME
   */
  public void setSalesName(String salesName) {
    this.salesName = salesName;
  }

  /**
   * @return DOB
   */
  public String getDob() {
    return dob;
  }

  /**
   * @param DOB
   */
  public void setDob(String dob) {
    this.dob = dob;
  }

  /**
   * @return CHINESE_ID
   */
  public String getChineseId() {
    return chineseId;
  }

  /**
   * @param CHINESE_ID
   */
  public void setChineseId(String chineseId) {
    this.chineseId = chineseId;
  }

  /**
   * @return PASSPORT
   */
  public String getPassport() {
    return passport;
  }

  /**
   * @param PASSPORT
   */
  public void setPassport(String passport) {
    this.passport = passport;
  }

  /**
   * @return UNIVERSITY
   */
  public String getUniversity() {
    return university;
  }

  /**
   * @param UNIVERSITY
   */
  public void setUniversity(String university) {
    this.university = university;
  }

  /**
   * @return SCHOOL
   */
  public String getSchool() {
    return school;
  }

  /**
   * @param SCHOOL
   */
  public void setSchool(String school) {
    this.school = school;
  }

  /**
   * @return DEPARTMENT
   */
  public String getDepartment() {
    return department;
  }

  /**
   * @param DEPARTMENT
   */
  public void setDepartment(String department) {
    this.department = department;
  }

  /**
   * @return SCHOOL_EMAIL
   */
  public String getSchoolEmail() {
    return schoolEmail;
  }

  /**
   * @param SCHOOL_EMAIL
   */
  public void setSchoolEmail(String schoolEmail) {
    this.schoolEmail = schoolEmail;
  }

  /**
   * @return PERSONAL_EMAIL
   */
  public String getPersonalEmail() {
    return personalEmail;
  }

  /**
   * @param PERSONAL_EMAIL
   */
  public void setPersonalEmail(String personalEmail) {
    this.personalEmail = personalEmail;
  }

  /**
   * @return WECHAT_ID
   */
  public String getWechatId() {
    return wechatId;
  }

  /**
   * @param WECHAT_ID
   */
  public void setWechatId(String wechatId) {
    this.wechatId = wechatId;
  }

  /**
   * @return CHINESE_HOME_ADDRESS
   */
  public String getChineseHomeAddress() {
    return chineseHomeAddress;
  }

  /**
   * @param CHINESE_HOME_ADDRESS
   */
  public void setChineseHomeAddress(String chineseHomeAddress) {
    this.chineseHomeAddress = chineseHomeAddress;
  }

  /**
   * @return CHINESE_HOME_ZIP
   */
  public String getChineseHomeZip() {
    return chineseHomeZip;
  }

  /**
   * @param CHINESE_HOME_ZIP
   */
  public void setChineseHomeZip(String chineseHomeZip) {
    this.chineseHomeZip = chineseHomeZip;
  }

  /**
   * @return CHINESE_HOME_TELEPHONE
   */
  public String getChineseHomeTelephone() {
    return chineseHomeTelephone;
  }

  /**
   * @param CHINESE_HOME_TELEPHONE
   */
  public void setChineseHomeTelephone(String chineseHomeTelephone) {
    this.chineseHomeTelephone = chineseHomeTelephone;
  }

  /**
   * @return CHINESE_HOME_CELLPHONE
   */
  public String getChineseHomeCellphone() {
    return chineseHomeCellphone;
  }

  /**
   * @param CHINESE_HOME_CELLPHONE
   */
  public void setChineseHomeCellphone(String chineseHomeCellphone) {
    this.chineseHomeCellphone = chineseHomeCellphone;
  }

  /**
   * @return USA_HOME_ADDRESS
   */
  public String getUsaHomeAddress() {
    return usaHomeAddress;
  }

  /**
   * @param USA_HOME_ADDRESS
   */
  public void setUsaHomeAddress(String usaHomeAddress) {
    this.usaHomeAddress = usaHomeAddress;
  }

  /**
   * @return USA_HOME_CITY
   */
  public String getUsaHomeCity() {
    return usaHomeCity;
  }

  /**
   * @param USA_HOME_CITY
   */
  public void setUsaHomeCity(String usaHomeCity) {
    this.usaHomeCity = usaHomeCity;
  }

  /**
   * @return USA_HOME_STATE
   */
  public String getUsaHomeState() {
    return usaHomeState;
  }

  /**
   * @param USA_HOME_STATE
   */
  public void setUsaHomeState(String usaHomeState) {
    this.usaHomeState = usaHomeState;
  }

  /**
   * @return USA_HOME_ZIP
   */
  public String getUsaHomeZip() {
    return usaHomeZip;
  }

  /**
   * @param USA_HOME_ZIP
   */
  public void setUsaHomeZip(String usaHomeZip) {
    this.usaHomeZip = usaHomeZip;
  }

  /**
   * @return USA_HOME_TELEPHONE
   */
  public String getUsaHomeTelephone() {
    return usaHomeTelephone;
  }

  /**
   * @param USA_HOME_TELEPHONE
   */
  public void setUsaHomeTelephone(String usaHomeTelephone) {
    this.usaHomeTelephone = usaHomeTelephone;
  }

  /**
   * @return USA_HOME_CELLPHONE
   */
  public String getUsaHomeCellphone() {
    return usaHomeCellphone;
  }

  /**
   * @param USA_HOME_CELLPHONE
   */
  public void setUsaHomeCellphone(String usaHomeCellphone) {
    this.usaHomeCellphone = usaHomeCellphone;
  }

  /**
   * @return FATHER_CHINESE_NAME
   */
  public String getFatherChineseName() {
    return fatherChineseName;
  }

  /**
   * @param FATHER_CHINESE_NAME
   */
  public void setFatherChineseName(String fatherChineseName) {
    this.fatherChineseName = fatherChineseName;
  }

  /**
   * @return FATHER_ENGLISH_NAME
   */
  public String getFatherEnglishName() {
    return fatherEnglishName;
  }

  /**
   * @param FATHER_ENGLISH_NAME
   */
  public void setFatherEnglishName(String fatherEnglishName) {
    this.fatherEnglishName = fatherEnglishName;
  }

  /**
   * @return FATHER_ADDRESS
   */
  public String getFatherAddress() {
    return fatherAddress;
  }

  /**
   * @param FATHER_ADDRESS
   */
  public void setFatherAddress(String fatherAddress) {
    this.fatherAddress = fatherAddress;
  }

  /**
   * @return FATHER_TELEPHONE
   */
  public String getFatherTelephone() {
    return fatherTelephone;
  }

  /**
   * @param FATHER_TELEPHONE
   */
  public void setFatherTelephone(String fatherTelephone) {
    this.fatherTelephone = fatherTelephone;
  }

  /**
   * @return FATHER_CELLPHONE
   */
  public String getFatherCellphone() {
    return fatherCellphone;
  }

  /**
   * @param FATHER_CELLPHONE
   */
  public void setFatherCellphone(String fatherCellphone) {
    this.fatherCellphone = fatherCellphone;
  }

  /**
   * @return FATHER_WECHAT_ID
   */
  public String getFatherWechatId() {
    return fatherWechatId;
  }

  /**
   * @param FATHER_WECHAT_ID
   */
  public void setFatherWechatId(String fatherWechatId) {
    this.fatherWechatId = fatherWechatId;
  }

  /**
   * @return MOTHER_CHINESE_NAME
   */
  public String getMotherChineseName() {
    return motherChineseName;
  }

  /**
   * @param MOTHER_CHINESE_NAME
   */
  public void setMotherChineseName(String motherChineseName) {
    this.motherChineseName = motherChineseName;
  }

  /**
   * @return MOTHER_ENGLISH_NAME
   */
  public String getMotherEnglishName() {
    return motherEnglishName;
  }

  /**
   * @param MOTHER_ENGLISH_NAME
   */
  public void setMotherEnglishName(String motherEnglishName) {
    this.motherEnglishName = motherEnglishName;
  }

  /**
   * @return MOTHER_ADDRESS
   */
  public String getMotherAddress() {
    return motherAddress;
  }

  /**
   * @param MOTHER_ADDRESS
   */
  public void setMotherAddress(String motherAddress) {
    this.motherAddress = motherAddress;
  }

  /**
   * @return MOTHER_TELEPHONE
   */
  public String getMotherTelephone() {
    return motherTelephone;
  }

  /**
   * @param MOTHER_TELEPHONE
   */
  public void setMotherTelephone(String motherTelephone) {
    this.motherTelephone = motherTelephone;
  }

  /**
   * @return MOTHER_CELLPHONE
   */
  public String getMotherCellphone() {
    return motherCellphone;
  }

  /**
   * @param MOTHER_CELLPHONE
   */
  public void setMotherCellphone(String motherCellphone) {
    this.motherCellphone = motherCellphone;
  }

  /**
   * @return MOTHER_WECHAT_ID
   */
  public String getMotherWechatId() {
    return motherWechatId;
  }

  /**
   * @param MOTHER_WECHAT_ID
   */
  public void setMotherWechatId(String motherWechatId) {
    this.motherWechatId = motherWechatId;
  }

  /**
   * @return LANDLORD_CHINESE_NAME
   */
  public String getLandlordChineseName() {
    return landlordChineseName;
  }

  /**
   * @param LANDLORD_CHINESE_NAME
   */
  public void setLandlordChineseName(String landlordChineseName) {
    this.landlordChineseName = landlordChineseName;
  }

  /**
   * @return LANDLORD_ENGLISH_NAME
   */
  public String getLandlordEnglishName() {
    return landlordEnglishName;
  }

  /**
   * @param LANDLORD_ENGLISH_NAME
   */
  public void setLandlordEnglishName(String landlordEnglishName) {
    this.landlordEnglishName = landlordEnglishName;
  }

  /**
   * @return LANDLORD_ADDRESS
   */
  public String getLandlordAddress() {
    return landlordAddress;
  }

  /**
   * @param LANDLORD_ADDRESS
   */
  public void setLandlordAddress(String landlordAddress) {
    this.landlordAddress = landlordAddress;
  }

  /**
   * @return LANDLORD_CITY
   */
  public String getLandlordCity() {
    return landlordCity;
  }

  /**
   * @param LANDLORD_CITY
   */
  public void setLandlordCity(String landlordCity) {
    this.landlordCity = landlordCity;
  }

  /**
   * @return LANDLORD_STATE
   */
  public String getLandlordState() {
    return landlordState;
  }

  /**
   * @param LANDLORD_STATE
   */
  public void setLandlordState(String landlordState) {
    this.landlordState = landlordState;
  }

  /**
   * @return LANDLORD_ZIP
   */
  public String getLandlordZip() {
    return landlordZip;
  }

  /**
   * @param LANDLORD_ZIP
   */
  public void setLandlordZip(String landlordZip) {
    this.landlordZip = landlordZip;
  }

  /**
   * @return LANDLORD_TELEPHONE
   */
  public String getLandlordTelephone() {
    return landlordTelephone;
  }

  /**
   * @param LANDLORD_TELEPHONE
   */
  public void setLandlordTelephone(String landlordTelephone) {
    this.landlordTelephone = landlordTelephone;
  }

  /**
   * @return LANDLORD_CELLPHONE
   */
  public String getLandlordCellphone() {
    return landlordCellphone;
  }

  /**
   * @param LANDLORD_CELLPHONE
   */
  public void setLandlordCellphone(String landlordCellphone) {
    this.landlordCellphone = landlordCellphone;
  }

  /**
   * @return LANDLORD_WECHAT_ID
   */
  public String getLandlordWechatId() {
    return landlordWechatId;
  }

  /**
   * @param LANDLORD_WECHAT_ID
   */
  public void setLandlordWechatId(String landlordWechatId) {
    this.landlordWechatId = landlordWechatId;
  }

  /**
   * @return ROOMMATE_CHINESE_NAME
   */
  public String getRoommateChineseName() {
    return roommateChineseName;
  }

  /**
   * @param ROOMMATE_CHINESE_NAME
   */
  public void setRoommateChineseName(String roommateChineseName) {
    this.roommateChineseName = roommateChineseName;
  }

  /**
   * @return ROOMMATE_ENGLISH_NAME
   */
  public String getRoommateEnglishName() {
    return roommateEnglishName;
  }

  /**
   * @param ROOMMATE_ENGLISH_NAME
   */
  public void setRoommateEnglishName(String roommateEnglishName) {
    this.roommateEnglishName = roommateEnglishName;
  }

  /**
   * @return ROOMMATE_ADDRESS
   */
  public String getRoommateAddress() {
    return roommateAddress;
  }

  /**
   * @param ROOMMATE_ADDRESS
   */
  public void setRoommateAddress(String roommateAddress) {
    this.roommateAddress = roommateAddress;
  }

  /**
   * @return ROOMMATE_CITY
   */
  public String getRoommateCity() {
    return roommateCity;
  }

  /**
   * @param ROOMMATE_CITY
   */
  public void setRoommateCity(String roommateCity) {
    this.roommateCity = roommateCity;
  }

  /**
   * @return ROOMMATE_STATE
   */
  public String getRoommateState() {
    return roommateState;
  }

  /**
   * @param ROOMMATE_STATE
   */
  public void setRoommateState(String roommateState) {
    this.roommateState = roommateState;
  }

  /**
   * @return ROOMMATE_ZIP
   */
  public String getRoommateZip() {
    return roommateZip;
  }

  /**
   * @param ROOMMATE_ZIP
   */
  public void setRoommateZip(String roommateZip) {
    this.roommateZip = roommateZip;
  }

  /**
   * @return ROOMMATE_TELEPHONE
   */
  public String getRoommateTelephone() {
    return roommateTelephone;
  }

  /**
   * @param ROOMMATE_TELEPHONE
   */
  public void setRoommateTelephone(String roommateTelephone) {
    this.roommateTelephone = roommateTelephone;
  }

  /**
   * @return ROOMMATE_CELLPHONE
   */
  public String getRoommateCellphone() {
    return roommateCellphone;
  }

  /**
   * @param ROOMMATE_CELLPHONE
   */
  public void setRoommateCellphone(String roommateCellphone) {
    this.roommateCellphone = roommateCellphone;
  }

  /**
   * @return NEIGHBOR_CHINESE_NAME
   */
  public String getNeighborChineseName() {
    return neighborChineseName;
  }

  /**
   * @param NEIGHBOR_CHINESE_NAME
   */
  public void setNeighborChineseName(String neighborChineseName) {
    this.neighborChineseName = neighborChineseName;
  }

  /**
   * @return NEIGHBOR_ENGLISH_NAME
   */
  public String getNeighborEnglishName() {
    return neighborEnglishName;
  }

  /**
   * @param NEIGHBOR_ENGLISH_NAME
   */
  public void setNeighborEnglishName(String neighborEnglishName) {
    this.neighborEnglishName = neighborEnglishName;
  }

  /**
   * @return NEIGHBOR_ADDRESS
   */
  public String getNeighborAddress() {
    return neighborAddress;
  }

  /**
   * @param NEIGHBOR_ADDRESS
   */
  public void setNeighborAddress(String neighborAddress) {
    this.neighborAddress = neighborAddress;
  }

  /**
   * @return NEIGHBOR_CITY
   */
  public String getNeighborCity() {
    return neighborCity;
  }

  /**
   * @param NEIGHBOR_CITY
   */
  public void setNeighborCity(String neighborCity) {
    this.neighborCity = neighborCity;
  }

  /**
   * @return NEIGHBOR_STATE
   */
  public String getNeighborState() {
    return neighborState;
  }

  /**
   * @param NEIGHBOR_STATE
   */
  public void setNeighborState(String neighborState) {
    this.neighborState = neighborState;
  }

  /**
   * @return NEIGHBOR_ZIP
   */
  public String getNeighborZip() {
    return neighborZip;
  }

  /**
   * @param NEIGHBOR_ZIP
   */
  public void setNeighborZip(String neighborZip) {
    this.neighborZip = neighborZip;
  }

  /**
   * @return NEIGHBOR_TELEPHONE
   */
  public String getNeighborTelephone() {
    return neighborTelephone;
  }

  /**
   * @param NEIGHBOR_TELEPHONE
   */
  public void setNeighborTelephone(String neighborTelephone) {
    this.neighborTelephone = neighborTelephone;
  }

  /**
   * @return NEIGHBOR_CELLPHONE
   */
  public String getNeighborCellphone() {
    return neighborCellphone;
  }

  /**
   * @param NEIGHBOR_CELLPHONE
   */
  public void setNeighborCellphone(String neighborCellphone) {
    this.neighborCellphone = neighborCellphone;
  }

  /**
   * @return OTHER_CHINESE_NAME
   */
  public String getOtherChineseName() {
    return otherChineseName;
  }

  /**
   * @param OTHER_CHINESE_NAME
   */
  public void setOtherChineseName(String otherChineseName) {
    this.otherChineseName = otherChineseName;
  }

  /**
   * @return OTHER_ENGLISH_NAME
   */
  public String getOtherEnglishName() {
    return otherEnglishName;
  }

  /**
   * @param OTHER_ENGLISH_NAME
   */
  public void setOtherEnglishName(String otherEnglishName) {
    this.otherEnglishName = otherEnglishName;
  }

  /**
   * @return OTHER_ADDRESS
   */
  public String getOtherAddress() {
    return otherAddress;
  }

  /**
   * @param OTHER_ADDRESS
   */
  public void setOtherAddress(String otherAddress) {
    this.otherAddress = otherAddress;
  }

  /**
   * @return OTHER_CITY
   */
  public String getOtherCity() {
    return otherCity;
  }

  /**
   * @param OTHER_CITY
   */
  public void setOtherCity(String otherCity) {
    this.otherCity = otherCity;
  }

  /**
   * @return OTHER_STATE
   */
  public String getOtherState() {
    return otherState;
  }

  /**
   * @param OTHER_STATE
   */
  public void setOtherState(String otherState) {
    this.otherState = otherState;
  }

  /**
   * @return OTHER_ZIP
   */
  public String getOtherZip() {
    return otherZip;
  }

  /**
   * @param OTHER_ZIP
   */
  public void setOtherZip(String otherZip) {
    this.otherZip = otherZip;
  }

  /**
   * @return OTHER_TELEPHONE
   */
  public String getOtherTelephone() {
    return otherTelephone;
  }

  /**
   * @param OTHER_TELEPHONE
   */
  public void setOtherTelephone(String otherTelephone) {
    this.otherTelephone = otherTelephone;
  }

  /**
   * @return OTHER_CELLPHONE
   */
  public String getOtherCellphone() {
    return otherCellphone;
  }

  /**
   * @param OTHER_CELLPHONE
   */
  public void setOtherCellphone(String otherCellphone) {
    this.otherCellphone = otherCellphone;
  }

  /**
   * @return SPECIAL
   */
  public Byte getSpecial() {
    return special;
  }

  /**
   * @param SPECIAL
   */
  public void setSpecial(Byte special) {
    this.special = special;
  }

  /**
   * @return SPECIAL_COMMENT
   */
  public String getSpecialComment() {
    return specialComment;
  }

  /**
   * @param SPECIAL_COMMENT
   */
  public void setSpecialComment(String specialComment) {
    this.specialComment = specialComment;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
