package com.lumei.crm.customer.entity;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Jul 30 23:58:18 CST 2016
 */
public class TFiles extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field USER_ID
   */
  private String userId;

  /**
   * @field SERVICE_TYPE
   */
  private String serviceType;

  /**
   * @field URI
   */
  private String uri;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return USER_ID
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param USER_ID
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return SERVICE_TYPE
   */
  public String getServiceType() {
    return serviceType;
  }

  /**
   * @param SERVICE_TYPE
   */
  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }

  /**
   * @return URI
   */
  public String getUri() {
    return uri;
  }

  /**
   * @param URI
   */
  public void setUri(String uri) {
    this.uri = uri;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
