package com.lumei.crm.customer.entity;

import java.util.Date;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Jul 30 23:58:18 CST 2016
 */
public class TNotes extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field NOTE_SERVICE_TYPE
   */
  private String noteServiceType;

  /**
   * @field USER_ID
   */
  private String userId;

  /**
   * @field COMMIT_USER_ID
   */
  private String commitUserId;

  /**
   * @field COMMIT_TIME
   */
  private Date commitTime;

  /**
   * @field CONTENT
   */
  private String content;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return NOTE_SERVICE_TYPE
   */
  public String getNoteServiceType() {
    return noteServiceType;
  }

  /**
   * @param NOTE_SERVICE_TYPE
   */
  public void setNoteServiceType(String noteServiceType) {
    this.noteServiceType = noteServiceType;
  }

  /**
   * @return USER_ID
   */
  public String getUserId() {
    return userId;
  }

  /**
   * @param USER_ID
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * @return COMMIT_USER_ID
   */
  public String getCommitUserId() {
    return commitUserId;
  }

  /**
   * @param COMMIT_USER_ID
   */
  public void setCommitUserId(String commitUserId) {
    this.commitUserId = commitUserId;
  }

  /**
   * @return COMMIT_TIME
   */
  public Date getCommitTime() {
    return commitTime;
  }

  /**
   * @param COMMIT_TIME
   */
  public void setCommitTime(Date commitTime) {
    this.commitTime = commitTime;
  }

  /**
   * @return CONTENT
   */
  public String getContent() {
    return content;
  }

  /**
   * @param CONTENT
   */
  public void setContent(String content) {
    this.content = content;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
