package com.lumei.crm.customer.entity;

import java.util.Date;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Jul 30 23:58:18 CST 2016
 */
public class TProfile extends BaseEntity<String> {

  /**
   * @field ID
   */
  private String id;

  /**
   * @field NAME
   */
  private String name;

  /**
   * @field GENDER
   */
  private Short gender;

  /**
   * @field PHONE
   */
  private String phone;

  /**
   * @field EMAIL
   */
  private String email;

  /**
   * @field STREET
   */
  private String street;

  /**
   * @field CITY
   */
  private String city;

  /**
   * @field STATE
   */
  private String state;

  /**
   * @field ZIP_CODE
   */
  private String zipCode;

  /**
   * @field UNIVERSITY
   */
  private String university;

  /**
   * @field STATUS
   */
  private String status;

  /**
   * @field DEPOSIT
   */
  private String deposit;

  /**
   * @field WHEN_TO_BUY
   */
  private String whenToBuy;

  /**
   * @field CASH_DEAL
   */
  private String cashDeal;

  /**
   * @field FINANCE
   */
  private String finance;

  /**
   * @field LEASING
   */
  private String leasing;

  /**
   * @field CATEGORY
   */
  private String category;

  /**
   * @field SERVICE
   */
  private String service;

  /**
   * @field EFFECT_DATE
   */
  private Date effectDate;

  /**
   * @field EXPERIATION_DATE
   */
  private Date experiationDate;

  /**
   * @field TOTAL_EVENTS
   */
  private Integer totalEvents;

  /**
   * @field USED_EVENTS
   */
  private Integer usedEvents;

  /**
   * @field DELETE_FLAG
   */
  private Byte deleteFlag;

  /**
   * @return ID
   */
  public String getId() {
    return id;
  }

  /**
   * @param ID
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * @return NAME
   */
  public String getName() {
    return name;
  }

  /**
   * @param NAME
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * @return GENDER
   */
  public Short getGender() {
    return gender;
  }

  /**
   * @param GENDER
   */
  public void setGender(Short gender) {
    this.gender = gender;
  }

  /**
   * @return PHONE
   */
  public String getPhone() {
    return phone;
  }

  /**
   * @param PHONE
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * @return EMAIL
   */
  public String getEmail() {
    return email;
  }

  /**
   * @param EMAIL
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * @return STREET
   */
  public String getStreet() {
    return street;
  }

  /**
   * @param STREET
   */
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   * @return CITY
   */
  public String getCity() {
    return city;
  }

  /**
   * @param CITY
   */
  public void setCity(String city) {
    this.city = city;
  }

  /**
   * @return STATE
   */
  public String getState() {
    return state;
  }

  /**
   * @param STATE
   */
  public void setState(String state) {
    this.state = state;
  }

  /**
   * @return ZIP_CODE
   */
  public String getZipCode() {
    return zipCode;
  }

  /**
   * @param ZIP_CODE
   */
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  /**
   * @return UNIVERSITY
   */
  public String getUniversity() {
    return university;
  }

  /**
   * @param UNIVERSITY
   */
  public void setUniversity(String university) {
    this.university = university;
  }

  /**
   * @return STATUS
   */
  public String getStatus() {
    return status;
  }

  /**
   * @param STATUS
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * @return DEPOSIT
   */
  public String getDeposit() {
    return deposit;
  }

  /**
   * @param DEPOSIT
   */
  public void setDeposit(String deposit) {
    this.deposit = deposit;
  }

  /**
   * @return WHEN_TO_BUY
   */
  public String getWhenToBuy() {
    return whenToBuy;
  }

  /**
   * @param WHEN_TO_BUY
   */
  public void setWhenToBuy(String whenToBuy) {
    this.whenToBuy = whenToBuy;
  }

  /**
   * @return CASH_DEAL
   */
  public String getCashDeal() {
    return cashDeal;
  }

  /**
   * @param CASH_DEAL
   */
  public void setCashDeal(String cashDeal) {
    this.cashDeal = cashDeal;
  }

  /**
   * @return FINANCE
   */
  public String getFinance() {
    return finance;
  }

  /**
   * @param FINANCE
   */
  public void setFinance(String finance) {
    this.finance = finance;
  }

  /**
   * @return LEASING
   */
  public String getLeasing() {
    return leasing;
  }

  /**
   * @param LEASING
   */
  public void setLeasing(String leasing) {
    this.leasing = leasing;
  }

  /**
   * @return CATEGORY
   */
  public String getCategory() {
    return category;
  }

  /**
   * @param CATEGORY
   */
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   * @return SERVICE
   */
  public String getService() {
    return service;
  }

  /**
   * @param SERVICE
   */
  public void setService(String service) {
    this.service = service;
  }

  /**
   * @return EFFECT_DATE
   */
  public Date getEffectDate() {
    return effectDate;
  }

  /**
   * @param EFFECT_DATE
   */
  public void setEffectDate(Date effectDate) {
    this.effectDate = effectDate;
  }

  /**
   * @return EXPERIATION_DATE
   */
  public Date getExperiationDate() {
    return experiationDate;
  }

  /**
   * @param EXPERIATION_DATE
   */
  public void setExperiationDate(Date experiationDate) {
    this.experiationDate = experiationDate;
  }

  /**
   * @return TOTAL_EVENTS
   */
  public Integer getTotalEvents() {
    return totalEvents;
  }

  /**
   * @param TOTAL_EVENTS
   */
  public void setTotalEvents(Integer totalEvents) {
    this.totalEvents = totalEvents;
  }

  /**
   * @return USED_EVENTS
   */
  public Integer getUsedEvents() {
    return usedEvents;
  }

  /**
   * @param USED_EVENTS
   */
  public void setUsedEvents(Integer usedEvents) {
    this.usedEvents = usedEvents;
  }

  /**
   * @return DELETE_FLAG
   */
  public Byte getDeleteFlag() {
    return deleteFlag;
  }

  /**
   * @param DELETE_FLAG
   */
  public void setDeleteFlag(Byte deleteFlag) {
    this.deleteFlag = deleteFlag;
  }
}
