package com.lumei.crm.customer.entity;

import com.lumei.crm.commons.dao.support.BaseEntity;

/**
 * 
 * @generated by Code Generator v0.1
 * @date Sat Aug 20 11:58:51 CST 2016
 */
public class TSequence extends BaseEntity<String> {

  /**
   * @field NAME
   */
  private String name;

  /**
   * @field CURRENT_VALUE
   */
  private Integer currentValue;

  /**
   * @field INCREMENT
   */
  private Integer increment;

  /**
   * @return NAME
   */
  public String getName() {
    return name;
  }

  /**
   * @param NAME
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * @return CURRENT_VALUE
   */
  public Integer getCurrentValue() {
    return currentValue;
  }

  /**
   * @param CURRENT_VALUE
   */
  public void setCurrentValue(Integer currentValue) {
    this.currentValue = currentValue;
  }

  /**
   * @return INCREMENT
   */
  public Integer getIncrement() {
    return increment;
  }

  /**
   * @param INCREMENT
   */
  public void setIncrement(Integer increment) {
    this.increment = increment;
  }

@Override
public String getId() {
	return name;
}
  
}
